local Venyx = loadstring(game:HttpGet("https://raw.githubusercontent.com/Stefanuk12/Venyx-UI-Library/main/source2.lua"))()
local UI = Venyx.new("Venyx Test 🔥")
local Tab = UI.newTab("Main")
Tab.newToggle("Auto Farm", false, function(state) print("Farm:", state) end)
Tab.newButton("Test", function() Venyx:Notify("Keren!", "Smooth anim!") end)
