-- @XKID SCRIPT v5.5 (Rapi)
-- by @WTF.XKID | Roblox Build For Mobile | WindUI Footagesus
repeat task.wait() until game:IsLoaded()

if not table.clear then function table.clear(t) for i=#t,1,-1 do t[i]=nil end end end
math.randomseed(tick()*1000+game:GetService("Players").LocalPlayer.UserId)

local WindUI = pcall(loadstring(game:HttpGet("https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"))) and (function() return _ end)() or error("Failed to load WindUI")

local RS,Http,TS,Players,UIS,VirtualUser,Lighting,TPService,Stats,CoreGui,TextChat,StarterGui,ReplicatedStorage = game:GetService("RunService"),game:GetService("HttpService"),game:GetService("TweenService"),game:GetService("Players"),game:GetService("UserInputService"),pcall(function() return game:GetService("VirtualUser") end) and game:GetService("VirtualUser") or nil,game:GetService("Lighting"),game:GetService("TeleportService"),game:GetService("Stats"),game:GetService("CoreGui"),game:GetService("TextChatService"),game:GetService("StarterGui"),game:GetService("ReplicatedStorage")
local LP, Cam, onMobile = Players.LocalPlayer, workspace.CurrentCamera, not UIS.KeyboardEnabled
local CURRENT_VERSION, _UI_LOADING = "5.5", true; getgenv()._XKID_UI_LOADING = true

local originalLighting = {ClockTime=Lighting.ClockTime, Brightness=Lighting.Brightness, Ambient=Lighting.Ambient, OutdoorAmbient=Lighting.OutdoorAmbient, GlobalShadows=Lighting.GlobalShadows, ExposureCompensation=Lighting.ExposureCompensation, FogEnd=Lighting.FogEnd}

if getgenv()._XKID_RUNNING then getgenv()._XKID_RUNNING=false; task.wait(0.5) end
if getgenv()._XKID_ESP_CACHE then for _,c in pairs(getgenv()._XKID_ESP_CACHE) do pcall(function() if c.texts then c.texts:Remove() end; if c.tracer then c.tracer:Remove() end; if c.boxLines then for _,l in ipairs(c.boxLines) do l:Remove() end end; if c.hl then c.hl:Destroy() end end) end end
getgenv()._XKID_ESP_CACHE={}
if getgenv()._XKID_LOADED then
    pcall(function() for _,v in pairs(CoreGui:GetChildren()) do if v.Name:match("XKID_") or v.Name=="WindUI" then v:Destroy() end end; for _,v in pairs(Lighting:GetChildren()) do if v.Name=="_XKID_FILTER" or v.Name=="_XKID_DOF" then v:Destroy() end end; if getgenv()._XKID_CONNS then for _,c in pairs(getgenv()._XKID_CONNS) do pcall(function() c:Disconnect() end) end end end)
    pcall(function() RS:UnbindFromRenderStep("XKIDFreecam") end); pcall(function() RS:UnbindFromRenderStep("XKIDFly") end); pcall(function() RS:UnbindFromRenderStep("XKIDSpec") end); pcall(function() RS:UnbindFromRenderStep("XKIDSelfSpec") end); pcall(function() RS:UnbindFromRenderStep("XKIDShiftLock") end); pcall(function() RS:UnbindFromRenderStep("XKIDAutoWalk") end)
end
getgenv()._XKID_LOADED, getgenv()._XKID_RUNNING, getgenv()._XKID_CONNS = true, true, {}
local function TrackC(c) table.insert(getgenv()._XKID_CONNS,c); return c end
local function notify(t,c,d,i) local ok=pcall(function() WindUI:Notify({Title=t,Content=c,Duration=d or 2,Icon=i or"bell"}) end); if not ok then task.wait(0.03); pcall(function() WindUI:Notify({Title=t,Content=c,Duration=d or 2,Icon=i or"bell"}) end) end end

local State = { Move={ws=16,jp=50,ncp=false,infJ=false,flyS=60,autoWalk=false,autoWalkSpeed=16}, Fly={active=false,bv=nil,bg=nil,_keys={}}, HardFling={active=false,power=10000,mode="Spin",currentPower=0,rampUpActive=false}, Security={afkActive=false,shiftLock=false,shiftLockGyro=nil,antiLag=false}, Cinema={hideUI=false,cachedGuis={}}, Avatar={isRefreshing=false}, Utility={chatLog=false,chatTargets={},chatHistory={}}, AutoLike={active=false,thread=nil,lastTarget=nil,count=0,radius=100,minCD=2,maxCD=6}, CustomFilter={tintR=255,tintG=255,tintB=255,saturation=0,contrast=0,brightness=0,exposure=0,bloomIntensity=0,bloomSize=24,clockTime=14,dofIntensity=0,dofDistance=50}, SelfSpec={active=false,mode="Manual",dist=8,height=3,orbitYaw=0,orbitPitch=20,fpYaw=0,fpPitch=0,fov=70,origFov=70,roll=0,radius=8,speed=1}, ESP={active=false,cache=getgenv()._XKID_ESP_CACHE,tracerMode="Bottom",maxDrawDistance=300,highlightMode=false,boxColor_N=Color3.fromRGB(0,255,150),boxColor_S=Color3.fromRGB(220,20,60),boxColor_G=Color3.fromRGB(255,165,0),tracerColor_N=Color3.fromRGB(0,200,255),tracerColor_S=Color3.fromRGB(220,20,60),tracerColor_G=Color3.fromRGB(255,165,0),nameColor=Color3.fromRGB(255,255,255)} }
local colorMap = {Merah=Color3.new(1,0,0), Hijau=Color3.new(0,1,0), Biru=Color3.new(0,0,1), Kuning=Color3.new(1,1,0), Ungu=Color3.new(1,0,1), Cyan=Color3.new(0,1,1), Orange=Color3.fromRGB(255,165,0), Pink=Color3.fromRGB(255,105,180), Putih=Color3.new(1,1,1), Hitam=Color3.new(0,0,0), Crimson=Color3.fromRGB(220,20,60)}
local function getRoot() return LP.Character and LP.Character:FindFirstChild("HumanoidRootPart") end
local function getHum() return LP.Character and LP.Character:FindFirstChildOfClass("Humanoid") end
local function getDisplayNames() local t={}; for _,p in pairs(Players:GetPlayers()) do if p~=LP then table.insert(t,p.DisplayName) end end; if #t==0 then table.insert(t,"N/A") end; return t end
local function getDisplayNamesWithSelf() local t={"[Self]"}; for _,p in pairs(Players:GetPlayers()) do if p~=LP then table.insert(t,p.DisplayName) end end; if #t==1 then table.insert(t,"N/A") end; return t end
local function findPlayerByDisplay(s) if s=="[Self]" then return LP end; for _,p in pairs(Players:GetPlayers()) do if p.DisplayName==s or p.Name==s then return p end end; return nil end
local function getCharRoot(c) if not c then return nil end; return c:FindFirstChild("HumanoidRootPart") or c.PrimaryPart or c:FindFirstChild("Head") or c:FindFirstChild("Torso") or c:FindFirstChild("UpperTorso") or c:FindFirstChildWhichIsA("BasePart") end
local function formatTime(s) local m=math.floor(s/60); return string.format("%02d:%02d",m,s%60) end
local function makeBar(v,m,l) local f=math.clamp(math.floor((v/m)*l),0,l); return string.rep("█",f)..string.rep("░",l-f) end
local function getConfigList() local l={}; pcall(function() if isfolder and isfolder("XKID_HUB") then for _,f in ipairs(listfiles("XKID_HUB")) do if f:match("%.json$") then local n=f:match("([^/\\]+)%.json$"); if n then table.insert(l,n) end end end end end); if #l==0 then table.insert(l,"No config") end; return l end
local function isOnGround() local r=getRoot(); if not r then return false end; local p=RaycastParams.new(); p.FilterType=Enum.RaycastFilterType.Exclude; p.FilterDescendantsInstances={LP.Character}; return workspace:Raycast(r.Position,Vector3.new(0,-5,0),p)~=nil end

local START_TIME, cachedMapName, lastMapCheck, sharedFPS, sharedPing = os.time(), nil, 0, 60, 0
TrackC(RS.RenderStepped:Connect(function(dt) if dt>0 then sharedFPS=math.floor(1/dt) end end))
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(0.5); pcall(function() local i=Stats.Network.ServerStatsItem["Data Ping"]; if i then sharedPing=math.floor(i:GetValue()) end end) end end)
task.spawn(function() while getgenv()._XKID_RUNNING do pcall(function() if tick()-lastMapCheck>30 or not cachedMapName then cachedMapName=game:GetService("MarketplaceService"):GetProductInfo(game.PlaceId).Name; lastMapCheck=tick() end end); task.wait(5) end end)
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(120); collectgarbage("collect") end end)
pcall(function() if setfpscap then setfpscap(9999) end end)
TrackC(LP.CharacterAdded:Connect(function() pcall(function() if setfpscap then setfpscap(9999) end end) end))
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(30); pcall(function() if setfpscap then setfpscap(9999) end end) end end)

-- ANTI AFK UNIVERSAL
local AntiAFK = {Active=false,IntervalMin=20,IntervalMax=35,Method="Camera",LastActivity=tick(),CurrentInterval=25,MainThread=nil,Listeners={},Camera=workspace.CurrentCamera}
local function resetTimer() AntiAFK.LastActivity=tick() end
local function addConnection(c) table.insert(AntiAFK.Listeners,c); return c end
local function cleanupConnections() for _,v in ipairs(AntiAFK.Listeners) do pcall(function() v:Disconnect() end) end; table.clear(AntiAFK.Listeners) end
local function randomInterval() return math.random(AntiAFK.IntervalMin,AntiAFK.IntervalMax) end
local function wiggleCamera() local cam=AntiAFK.Camera; if not cam then return end; pcall(function() local cf=cam.CFrame; local yaw=math.random(2,5); local target=CFrame.new(cf.Position)*CFrame.Angles(0,math.rad(yaw),0); cam.CFrame=target; task.wait(0.05); cam.CFrame=cf end) end
local function microMovement() local c=LP.Character; if not c then return end; local h=c:FindFirstChild("HumanoidRootPart"); if not h then return end; pcall(function() local o=h.CFrame; local d=AntiAFK.Camera and AntiAFK.Camera.CFrame.LookVector or Vector3.new(0,0,-1); h.CFrame=o+(d*0.1); task.wait(0.05); h.CFrame=o end) end
local function executeActivity() if AntiAFK.Method=="Camera" then wiggleCamera() elseif AntiAFK.Method=="Movement" then microMovement() elseif AntiAFK.Method=="Both" then wiggleCamera(); task.wait(0.08); microMovement() elseif AntiAFK.Method=="Adaptive" then if math.random()>0.5 then wiggleCamera() else microMovement() end end end
local function setupInputListeners() addConnection(UIS.InputBegan:Connect(resetTimer)); addConnection(UIS.InputEnded:Connect(resetTimer)); addConnection(UIS.TouchStarted:Connect(resetTimer)); addConnection(UIS.TouchMoved:Connect(resetTimer)); addConnection(LP.CharacterAdded:Connect(resetTimer)); addConnection(RS.RenderStepped:Connect(function() if not AntiAFK.Active then return end; local c=LP.Character; local h=c and c:FindFirstChildOfClass("Humanoid"); if h and h.MoveDirection.Magnitude>0 then resetTimer() end end)) end
local function startMainLoop() if AntiAFK.MainThread then task.cancel(AntiAFK.MainThread) end; AntiAFK.MainThread=task.spawn(function() while AntiAFK.Active do if tick()-AntiAFK.LastActivity>=AntiAFK.CurrentInterval then pcall(executeActivity); AntiAFK.LastActivity=tick(); AntiAFK.CurrentInterval=randomInterval() end; task.wait(0.5) end end) end
local function startAFK() if AntiAFK.Active then return end; AntiAFK.Active=true; State.Security.afkActive=true; AntiAFK.Method="Camera"; AntiAFK.LastActivity=tick(); AntiAFK.CurrentInterval=randomInterval(); setupInputListeners(); startMainLoop(); notify("Anti AFK","ON (Universal)",1.5,"shield-check") end
local function stopAFK() AntiAFK.Active=false; State.Security.afkActive=false; if AntiAFK.MainThread then task.cancel(AntiAFK.MainThread); AntiAFK.MainThread=nil end; cleanupConnections(); notify("Anti AFK","OFF",1.5,"shield-check") end
function ToggleAntiAFK() if AntiAFK.Active then stopAFK() else startAFK() end end

-- SHIFT LOCK
TrackC(LP.CharacterAdded:Connect(function(c) task.wait(0.5); local h=c:FindFirstChildOfClass("Humanoid"); if h then if State.Move.ws~=16 then h.WalkSpeed=State.Move.ws end; if State.Move.jp~=50 then h.UseJumpPower=true; h.JumpPower=State.Move.jp end end; if State.Security.shiftLock then task.wait(0.2); local r=getRoot(); if r then if State.Security.shiftLockGyro then State.Security.shiftLockGyro:Destroy() end; State.Security.shiftLockGyro=Instance.new("BodyGyro",r); State.Security.shiftLockGyro.MaxTorque=Vector3.new(9e9,9e9,9e9); State.Security.shiftLockGyro.P=50000; State.Security.shiftLockGyro.D=1000 end end end))
local function toggleShiftLock(v) State.Security.shiftLock=v; if v then local r=getRoot(); if r then if State.Security.shiftLockGyro then State.Security.shiftLockGyro:Destroy() end; State.Security.shiftLockGyro=Instance.new("BodyGyro",r); State.Security.shiftLockGyro.MaxTorque=Vector3.new(9e9,9e9,9e9); State.Security.shiftLockGyro.P=50000; State.Security.shiftLockGyro.D=1000 end; RS:BindToRenderStep("XKIDShiftLock",Enum.RenderPriority.Camera.Value+2,function() if not State.Security.shiftLock then return end; local r2,g=getRoot(),State.Security.shiftLockGyro; if r2 and g and g.Parent==r2 then local f=Vector3.new(Cam.CFrame.LookVector.X,0,Cam.CFrame.LookVector.Z); if f.Magnitude>0.01 then g.CFrame=CFrame.new(r2.Position,r2.Position+f) end end end); notify("Shift Lock","ON",1.5,"lock") else RS:UnbindFromRenderStep("XKIDShiftLock"); if State.Security.shiftLockGyro then State.Security.shiftLockGyro:Destroy(); State.Security.shiftLockGyro=nil end; notify("Shift Lock","OFF",1.5,"unlock") end end

-- REFRESH CHARACTER
local pendingRefreshCF,pendingRefreshWS,pendingRefreshJP,pendingRefreshZoom=nil,16,50,400
local function refreshCharacter() if State.Avatar.isRefreshing then return end; local c=getRoot(); if not c then notify("Error","Character not found",2,"circle-alert"); return end; State.Avatar.isRefreshing=true; pendingRefreshCF=c.CFrame; pendingRefreshWS=State.Move.ws; pendingRefreshJP=State.Move.jp; pendingRefreshZoom=LP.CameraMaxZoomDistance; notify("Refresh","Reloading...",1.5,"refresh-cw"); pcall(function() LP.Character:BreakJoints() end); local w=0; repeat task.wait(0.1); w=w+0.1 until not LP.Character or w>2; if LP.Character then pcall(function() LP.Character:Destroy() end); task.wait(0.3) end; if not LP.Character then pcall(function() LP:LoadCharacter() end) end; task.delay(12,function() if State.Avatar.isRefreshing then State.Avatar.isRefreshing=false; pendingRefreshCF=nil; notify("Error","Refresh timeout",3,"circle-alert") end end) end
TrackC(LP.CharacterAdded:Connect(function(c) if not State.Avatar.isRefreshing or not pendingRefreshCF then return end; task.wait(0.3); local hrp=c:FindFirstChild("HumanoidRootPart") or c:WaitForChild("HumanoidRootPart",8); local hum=c:FindFirstChildOfClass("Humanoid") or c:WaitForChild("Humanoid",8); if hrp and hum then repeat task.wait() until hum.Health>0 and hrp:IsDescendantOf(workspace); hrp.CFrame=pendingRefreshCF+Vector3.new(0,4,0); hrp.AssemblyLinearVelocity=Vector3.zero; hrp.AssemblyAngularVelocity=Vector3.zero; hum.WalkSpeed=pendingRefreshWS; hum.UseJumpPower=true; hum.JumpPower=pendingRefreshJP; Cam.CameraSubject=hum; Cam.CameraType=Enum.CameraType.Custom; pcall(function() LP.CameraMaxZoomDistance=pendingRefreshZoom end); notify("Refresh","Done",2,"check-circle") end; State.Avatar.isRefreshing=false; pendingRefreshCF=nil end))

-- SMART TP
local Teleport={clickConn=nil,clickActive=false,toolActive=false,tool=nil}
local function executeTP() local r=getRoot(); if not r then return end; local m=LP:GetMouse(); if m.Hit then r.CFrame=CFrame.new(m.Hit.Position+Vector3.new(0,3.5,0)); r.AssemblyLinearVelocity=Vector3.zero end end
local function toggleSmartTP(v) Teleport.clickActive=v; if v then pcall(function() local t=Instance.new("Tool"); t.Name="TP Tool"; t.RequiresHandle=false; t.Parent=LP.Backpack; Teleport.tool=t; Teleport.toolActive=false; t.Activated:Connect(function() Teleport.toolActive=not Teleport.toolActive end) end); Teleport.clickConn=TrackC(UIS.InputBegan:Connect(function(inp,gp) if gp then return end; if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then if Teleport.toolActive then executeTP(); Teleport.toolActive=false end end end)); notify("Smart TP","ON",2,"map-pin") else if Teleport.clickConn then Teleport.clickConn:Disconnect(); Teleport.clickConn=nil end; pcall(function() if Teleport.tool then Teleport.tool:Destroy(); Teleport.tool=nil end end); Teleport.toolActive=false; notify("Smart TP","OFF",1.5,"map-pin") end end

-- AUTO WALK
local function startAutoWalk() RS:UnbindFromRenderStep("XKIDAutoWalk"); State.Move.autoWalk=true; local h=getHum(); if h then h.WalkSpeed=State.Move.autoWalkSpeed end; RS:BindToRenderStep("XKIDAutoWalk",Enum.RenderPriority.Character.Value+1,function() if not State.Move.autoWalk then return end; local r=getRoot(); local h=getHum(); if not r or not h then return end; if h.MoveDirection.Magnitude>0.1 then return end; local d=Cam.CFrame.LookVector; local m=Vector3.new(d.X,0,d.Z).Unit; r.CFrame=r.CFrame+m*(State.Move.autoWalkSpeed/60) end); notify("Auto Walk","ON",1.5,"play") end
local function stopAutoWalk() RS:UnbindFromRenderStep("XKIDAutoWalk"); State.Move.autoWalk=false; local h=getHum(); if h then h.WalkSpeed=State.Move.ws end; notify("Auto Walk","OFF",1.5,"play") end

-- ESP ENGINE
local function initPlayerCache(p) if State.ESP.cache[p] then return end; local c={texts=nil,tracer=nil,boxLines={},hl=nil,isSuspect=false,isGlitch=false,reason=""}; pcall(function() c.texts=Drawing.new("Text"); if c.texts then c.texts.Center=true; c.texts.Outline=true; c.texts.Font=2; c.texts.Size=13; c.texts.ZIndex=2 end; c.tracer=Drawing.new("Line"); if c.tracer then c.tracer.Thickness=1.5; c.tracer.ZIndex=1 end; for i=1,4 do local l=Drawing.new("Line"); if l then l.Thickness=1.5; l.ZIndex=1; c.boxLines[i]=l end end end); State.ESP.cache[p]=c end
local function clearPlayerCache(p) local c=State.ESP.cache[p]; if not c then return end; pcall(function() if c.texts then c.texts:Remove() end end); pcall(function() if c.tracer then c.tracer:Remove() end end); for _,l in ipairs(c.boxLines) do pcall(function() if l then l:Remove() end end) end; pcall(function() if c.hl then c.hl:Destroy() end end); State.ESP.cache[p]=nil end
TrackC(Players.PlayerRemoving:Connect(clearPlayerCache))
local espsortedPlayers={}
task.spawn(function() while getgenv()._XKID_RUNNING do if State.ESP.active then local t={}; local myH=getCharRoot(LP.Character); for _,p in pairs(Players:GetPlayers()) do if p~=LP and p.Character then local isSus,isGlitch,reason=false,false,""; for _,v in pairs(p.Character:GetChildren()) do if v:IsA("BasePart") and (v.Size.X>30 or v.Size.Y>30 or v.Size.Z>30) then isSus=true; reason="Map Blocker"; break elseif v:IsA("Accessory") then local h=v:FindFirstChild("Handle"); if h and h:IsA("BasePart") then if h.Size.Magnitude>20 then isSus=true; reason="Huge Hat"; break elseif h.Size.Magnitude>10 or (h.Transparency<0.1 and h.Material==Enum.Material.Neon) then isGlitch=true; reason="Glitch Acc" end end end end; if not isSus and not isGlitch then local hum=p.Character:FindFirstChildOfClass("Humanoid"); if hum then local bws,bhs=hum:FindFirstChild("BodyWidthScale"),hum:FindFirstChild("BodyHeightScale"); if (bws and bws.Value>2) or (bhs and bhs.Value>2) then isSus=true; reason="Glitch Avatar" end end end; initPlayerCache(p); if State.ESP.cache[p] then State.ESP.cache[p].isSuspect=isSus; State.ESP.cache[p].isGlitch=isGlitch; State.ESP.cache[p].reason=reason end; if myH then local hrp=getCharRoot(p.Character); local hum=p.Character:FindFirstChildOfClass("Humanoid"); if hrp and hum and hum.Health>0 then local d=(hrp.Position-myH.Position).Magnitude; if d<=State.ESP.maxDrawDistance then table.insert(t,{p=p,hrp=hrp,dist=d,char=p.Character}) end end end end end; table.sort(t,function(a,b) return a.dist<b.dist end); espsortedPlayers=t end; task.wait(0.5) end end)
TrackC(RS.RenderStepped:Connect(function() if not State.ESP.active then return end; local myH=getCharRoot(LP.Character); if not myH then return end; local vp=Cam.ViewportSize; local ctr=Vector2.new(vp.X/2,vp.Y/2); for _,c in pairs(State.ESP.cache) do pcall(function() if c.texts then c.texts.Visible=false end; if c.tracer then c.tracer.Visible=false end; for _,l in ipairs(c.boxLines) do if l then l.Visible=false end end; if c.hl then c.hl.Enabled=false end end) end; local hlC=0; for _,d in ipairs(espsortedPlayers) do local p,c,hrp,dist=d.p,d.char,d.hrp,d.dist; local ca=State.ESP.cache[p]; if not ca then continue end; local rp,on=Cam:WorldToViewportPoint(hrp.Position); if not on then continue end; local isSus,isGlitch=ca.isSuspect,ca.isGlitch; local useHl=isSus or isGlitch or State.ESP.highlightMode; local txt=string.format("%s\n[%dm]",p.DisplayName,math.floor(dist)); if isSus or isGlitch then txt=txt.."\n⚠ "..ca.reason end; local cCol=isSus and State.ESP.boxColor_S or (isGlitch and State.ESP.boxColor_G or State.ESP.nameColor); local tCol=isSus and State.ESP.tracerColor_S or (isGlitch and State.ESP.tracerColor_G or State.ESP.tracerColor_N); local bCol=isSus and State.ESP.boxColor_S or (isGlitch and State.ESP.boxColor_G or State.ESP.boxColor_N); pcall(function() if ca.texts then ca.texts.Text=txt; ca.texts.Color=cCol; ca.texts.Position=Vector2.new(rp.X,rp.Y-45); ca.texts.Visible=true end; if State.ESP.tracerMode~="OFF" and ca.tracer then local o=Vector2.new(vp.X/2,vp.Y); if State.ESP.tracerMode=="Center" then o=ctr elseif State.ESP.tracerMode=="Mouse" then local m=UIS:GetMouseLocation(); o=Vector2.new(m.X,m.Y) end; ca.tracer.From=o; ca.tracer.To=Vector2.new(rp.X,rp.Y); ca.tracer.Color=tCol; ca.tracer.Visible=true end end); if useHl and hlC<30 then hlC=hlC+1; pcall(function() local top,topOn=Cam:WorldToViewportPoint(hrp.Position+Vector3.new(0,3,0)); local bot,botOn=Cam:WorldToViewportPoint(hrp.Position-Vector3.new(0,3.5,0)); if topOn and botOn and #ca.boxLines==4 then local bh=math.abs(top.Y-bot.Y); local bw=bh*0.6; ca.boxLines[1].From=Vector2.new(rp.X-bw/2,top.Y); ca.boxLines[1].To=Vector2.new(rp.X+bw/2,top.Y); ca.boxLines[2].From=Vector2.new(rp.X+bw/2,top.Y); ca.boxLines[2].To=Vector2.new(rp.X+bw/2,bot.Y); ca.boxLines[3].From=Vector2.new(rp.X+bw/2,bot.Y); ca.boxLines[3].To=Vector2.new(rp.X-bw/2,bot.Y); ca.boxLines[4].From=Vector2.new(rp.X-bw/2,bot.Y); ca.boxLines[4].To=Vector2.new(rp.X-bw/2,top.Y); for i=1,4 do ca.boxLines[i].Color=bCol; ca.boxLines[i].Visible=true end end end); pcall(function() if not ca.hl or ca.hl.Parent~=c then if ca.hl then ca.hl:Destroy() end; ca.hl=Instance.new("Highlight",c); ca.hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop end; if ca.hl then ca.hl.FillColor=bCol; ca.hl.OutlineColor=Color3.new(1,1,1); ca.hl.Enabled=true end end) end end end))

-- FLY ENGINE
local flyMoveTouch,flyMoveSt,flyJoy,flyConns,flyVel=nil,nil,Vector2.zero,{},Vector3.zero
local function startFlyCapture() local kH={}; table.insert(flyConns,UIS.InputBegan:Connect(function(inp,gp) if gp then return end; local k=inp.KeyCode; if k==Enum.KeyCode.W or k==Enum.KeyCode.A or k==Enum.KeyCode.S or k==Enum.KeyCode.D or k==Enum.KeyCode.E or k==Enum.KeyCode.Q then kH[k]=true end end)); table.insert(flyConns,UIS.InputEnded:Connect(function(inp) kH[inp.KeyCode]=nil end)); table.insert(flyConns,UIS.InputBegan:Connect(function(inp,gp) if gp or inp.UserInputType~=Enum.UserInputType.Touch then return end; if inp.Position.X<=Cam.ViewportSize.X/2 then if not flyMoveTouch then flyMoveTouch=inp; flyMoveSt=inp.Position end end end)); table.insert(flyConns,UIS.TouchMoved:Connect(function(inp) if inp==flyMoveTouch and flyMoveSt then local dx,dy=inp.Position.X-flyMoveSt.X,inp.Position.Y-flyMoveSt.Y; flyJoy=Vector2.new(math.abs(dx)>25 and math.clamp((dx-math.sign(dx)*25)/80,-1,1) or 0, math.abs(dy)>20 and math.clamp((dy-math.sign(dy)*20)/80,-1,1) or 0) end end)); table.insert(flyConns,UIS.InputEnded:Connect(function(inp) if inp.UserInputType~=Enum.UserInputType.Touch then return end; if inp==flyMoveTouch then flyMoveTouch=nil; flyMoveSt=nil; flyJoy=Vector2.zero end end)); State.Fly._keys=kH end
local function stopFlyCapture() for _,c in ipairs(flyConns) do c:Disconnect() end; flyConns={}; flyMoveTouch=nil; flyMoveSt=nil; flyJoy=Vector2.zero; State.Fly._keys={} end
local function toggleFly(v) if not v then State.Fly.active=false; stopFlyCapture(); RS:UnbindFromRenderStep("XKIDFly"); pcall(function() if State.Fly.bv then State.Fly.bv:Destroy() end end); pcall(function() if State.Fly.bg then State.Fly.bg:Destroy() end end); State.Fly.bv=nil; State.Fly.bg=nil; flyVel=Vector3.zero; local h=getHum(); if h then h.PlatformStand=false; h:ChangeState(Enum.HumanoidStateType.GettingUp); h.WalkSpeed=State.Move.ws; h.UseJumpPower=true; h.JumpPower=State.Move.jp end; notify("Fly","OFF",1.5,"bird"); return end; local r,h=getRoot(),getHum(); if not r or not h then return end; State.Fly.active=true; h.PlatformStand=true; flyVel=Vector3.zero; State.Fly.bv=Instance.new("BodyVelocity",r); State.Fly.bv.MaxForce=Vector3.new(9e9,9e9,9e9); State.Fly.bg=Instance.new("BodyGyro",r); State.Fly.bg.MaxTorque=Vector3.new(9e9,9e9,9e9); State.Fly.bg.P=50000; startFlyCapture(); notify("Fly","ON",2,"bird"); RS:BindToRenderStep("XKIDFly",Enum.RenderPriority.Camera.Value+1,function() if not State.Fly.active then return end; local r2=getRoot(); if not r2 then return end; local cf=Cam.CFrame; local spd=State.Move.flyS; local mv=Vector3.zero; local keys=State.Fly._keys or {}; if onMobile then mv=cf.LookVector*(-flyJoy.Y)+cf.RightVector*flyJoy.X else if keys[Enum.KeyCode.W] then mv=mv+cf.LookVector end; if keys[Enum.KeyCode.S] then mv=mv-cf.LookVector end; if keys[Enum.KeyCode.D] then mv=mv+cf.RightVector end; if keys[Enum.KeyCode.A] then mv=mv-cf.RightVector end; if keys[Enum.KeyCode.E] then mv=mv+Vector3.new(0,1,0) end; if keys[Enum.KeyCode.Q] then mv=mv-Vector3.new(0,1,0) end end; if mv.Magnitude>0 then flyVel=flyVel:Lerp(mv.Unit*spd,0.15) else flyVel=flyVel:Lerp(isOnGround() and Vector3.zero or Vector3.new(0,-0.8,0),0.08) end; if State.Fly.bv and State.Fly.bv.Parent then State.Fly.bv.Velocity=flyVel end; if State.Fly.bg and State.Fly.bg.Parent then State.Fly.bg.CFrame=CFrame.new(r2.Position,r2.Position+cf.LookVector) end end) end

-- FREECAM (diringkas karena sangat panjang, fungsi tetap sama)
local FC={active=false,pos=Vector3.zero,pitchDeg=0,yawDeg=0,rollDeg=0,speed=3,sens=0.25,savedCF=nil,origFov=70,savedWalkSpeed=16,savedJumpPower=50,wasAnchored=false}
local I_CamVel,I_YawVel,I_PitchVel,I_RollVel,heightVelocity=Vector3.zero,0,0,0,0
local fcMoveTouch,fcMoveSt,fcJoy,fcRotTouch,fcRotLast,fcKeysHeld,fcConns=nil,nil,Vector2.zero,nil,nil,{},{}
local FC_UI_Btns={up=false,down=false,rollLeft=false,rollRight=false,zoomIn=false,zoomOut=false}
local FC_UI_Hidden,fcButtons=false,{}
local FCUI=Instance.new("ScreenGui"); FCUI.Name="XKID_FreecamUI"; FCUI.ResetOnSpawn=false; FCUI.ZIndexBehavior=Enum.ZIndexBehavior.Global; FCUI.Enabled=false; FCUI.Parent=CoreGui; getgenv()._XKID_FCUI=FCUI
local function makeFCBtn(n,t,p,a) local b=Instance.new("TextButton",FCUI); b.Name=n; b.Size=UDim2.new(0,44,0,44); b.Position=p; b.BackgroundColor3=Color3.fromRGB(15,15,15); b.BackgroundTransparency=0.4; b.Text=t; b.TextColor3=Color3.fromRGB(255,255,255); b.TextSize=18; b.Font=Enum.Font.GothamBold; b.AutoButtonColor=false; Instance.new("UICorner",b).CornerRadius=UDim.new(0,10); local uis=Instance.new("UIStroke",b); uis.Color=Color3.fromRGB(220,20,60); uis.Thickness=2; uis.Transparency=0.3; local ind=Instance.new("Frame",b); ind.Name="Indicator"; ind.Size=UDim2.new(0,6,0,6); ind.Position=UDim2.new(0,4,0,4); ind.BackgroundColor3=Color3.fromRGB(60,60,60); Instance.new("UICorner",ind).CornerRadius=UDim.new(1,0); local function press(d) FC_UI_Btns[a]=d; b.BackgroundTransparency=d and 0.05 or 0.4; ind.BackgroundColor3=d and Color3.fromRGB(255,60,60) or Color3.fromRGB(60,60,60) end; b.InputBegan:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then press(true) end end); b.InputEnded:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then press(false) end end); b.MouseLeave:Connect(function() press(false) end); table.insert(fcButtons,b); return b end
makeFCBtn("BtnRollL","L",UDim2.new(1,-156,0.5,-66),"rollLeft"); makeFCBtn("BtnRollR","R",UDim2.new(1,-58,0.5,-66),"rollRight"); makeFCBtn("BtnUp","↑",UDim2.new(1,-107,0.5,-110),"up"); makeFCBtn("BtnDown","↓",UDim2.new(1,-107,0.5,-22),"down"); makeFCBtn("BtnZIn","+",UDim2.new(1,-156,0.5,-22),"zoomIn"); makeFCBtn("BtnZOut","-",UDim2.new(1,-58,0.5,-22),"zoomOut")
local eyeBtn=Instance.new("TextButton",FCUI); eyeBtn.Name="BtnEye"; eyeBtn.Size=UDim2.new(0,44,0,44); eyeBtn.Position=UDim2.new(1,-107,0.5,-66); eyeBtn.BackgroundColor3=Color3.fromRGB(15,15,15); eyeBtn.BackgroundTransparency=0.6; eyeBtn.Text="👁"; eyeBtn.TextColor3=Color3.fromRGB(255,255,255); eyeBtn.TextSize=18; eyeBtn.Font=Enum.Font.GothamBold; eyeBtn.AutoButtonColor=false; Instance.new("UICorner",eyeBtn).CornerRadius=UDim.new(0,10); Instance.new("UIStroke",eyeBtn).Color=Color3.fromRGB(220,20,60)
local function toggleFCEye() FC_UI_Hidden=not FC_UI_Hidden; eyeBtn.Text=FC_UI_Hidden and "👁‍🗨" or "👁"; for _,b in ipairs(fcButtons) do b.Visible=not FC_UI_Hidden end end
eyeBtn.MouseButton1Click:Connect(toggleFCEye); eyeBtn.InputBegan:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.Touch then toggleFCEye() end end)
local function startFreecamCapture() fcKeysHeld={}; table.insert(fcConns,UIS.InputBegan:Connect(function(inp,gp) if gp then return end; fcKeysHeld[inp.KeyCode]=true; if inp.UserInputType==Enum.UserInputType.MouseButton2 then FC._mouseRot=true; UIS.MouseBehavior=Enum.MouseBehavior.LockCurrentPosition end end)); table.insert(fcConns,UIS.InputEnded:Connect(function(inp) fcKeysHeld[inp.KeyCode]=false; if inp.UserInputType==Enum.UserInputType.MouseButton2 then FC._mouseRot=false; UIS.MouseBehavior=Enum.MouseBehavior.Default end end)); table.insert(fcConns,UIS.InputChanged:Connect(function(inp) if inp.UserInputType==Enum.UserInputType.MouseMovement and FC._mouseRot then I_YawVel=I_YawVel-inp.Delta.X*FC.sens*120; I_PitchVel=I_PitchVel-inp.Delta.Y*FC.sens*120 end end)); table.insert(fcConns,UIS.InputBegan:Connect(function(inp,gp) if gp or inp.UserInputType~=Enum.UserInputType.Touch then return end; if inp.Position.X>Cam.ViewportSize.X/2 then if not fcRotTouch then fcRotTouch=inp; fcRotLast=inp.Position end else if not fcMoveTouch then fcMoveTouch=inp; fcMoveSt=inp.Position; fcJoy=Vector2.zero end end end)); table.insert(fcConns,UIS.TouchMoved:Connect(function(inp) if inp==fcRotTouch and fcRotLast then local dx,dy=inp.Position.X-fcRotLast.X,inp.Position.Y-fcRotLast.Y; fcRotLast=inp.Position; I_YawVel=I_YawVel-dx*FC.sens*80; I_PitchVel=I_PitchVel-dy*FC.sens*80 end; if inp==fcMoveTouch and fcMoveSt then local dx,dy=inp.Position.X-fcMoveSt.X,inp.Position.Y-fcMoveSt.Y; local function ad(v,d,m) if math.abs(v)<d then return 0 end; return math.clamp((v-math.sign(v)*d)/(m-d),-1,1) end; fcJoy=Vector2.new(ad(dx,15,70),ad(dy,15,70)) end end)); table.insert(fcConns,UIS.InputEnded:Connect(function(inp) if inp.UserInputType~=Enum.UserInputType.Touch then return end; if inp==fcRotTouch then fcRotTouch=nil; fcRotLast=nil end; if inp==fcMoveTouch then fcMoveTouch=nil; fcMoveSt=nil; fcJoy=Vector2.zero end end)) end
local function stopFreecamCapture() for _,c in ipairs(fcConns) do c:Disconnect() end; fcConns={}; fcKeysHeld={}; FC._mouseRot=false; UIS.MouseBehavior=Enum.MouseBehavior.Default end
local function startFreecamLoop() RS:BindToRenderStep("XKIDFreecam",Enum.RenderPriority.Camera.Value+1,function(dt) if not FC.active then return end; Cam.CameraType=Enum.CameraType.Scriptable; local sdt=math.clamp(dt,0.001,0.05); I_YawVel=I_YawVel*math.max(0,1-sdt*14); I_PitchVel=I_PitchVel*math.max(0,1-sdt*14); FC.yawDeg=FC.yawDeg+I_YawVel*sdt; FC.pitchDeg=math.clamp(FC.pitchDeg+I_PitchVel*sdt,-80,80); local rT=0; if FC_UI_Btns.rollLeft then rT=-100 elseif FC_UI_Btns.rollRight then rT=100 end; I_RollVel=I_RollVel+(rT-I_RollVel)*math.clamp(sdt*5,0,1); FC.rollDeg=math.clamp(FC.rollDeg+I_RollVel*sdt,-100,100); local camCF=CFrame.new(FC.pos)*CFrame.Angles(0,math.rad(FC.yawDeg),0)*CFrame.Angles(math.rad(FC.pitchDeg),0,0); local jX,jY=fcJoy.X,fcJoy.Y; if not onMobile then if fcKeysHeld[Enum.KeyCode.W] then jY=jY-1 end; if fcKeysHeld[Enum.KeyCode.S] then jY=jY+1 end; if fcKeysHeld[Enum.KeyCode.D] then jX=jX+1 end; if fcKeysHeld[Enum.KeyCode.A] then jX=jX-1 end end; local rMove=Vector2.new(jX,jY); if rMove.Magnitude>1 then rMove=rMove.Unit end; I_CamVel=I_CamVel:Lerp((camCF.LookVector*(-rMove.Y)+camCF.RightVector*rMove.X)*(FC.speed*60),math.clamp(sdt*3.5,0,1)); local hT=0; if fcKeysHeld[Enum.KeyCode.E] or FC_UI_Btns.up then hT=FC.speed*60 end; if fcKeysHeld[Enum.KeyCode.Q] or FC_UI_Btns.down then hT=-FC.speed*60 end; if hT==0 then heightVelocity=heightVelocity*math.max(0,1-sdt*10) else heightVelocity=heightVelocity+(hT-heightVelocity)*math.clamp(sdt*3,0,1) end; if FC_UI_Btns.zoomIn then Cam.FieldOfView=math.clamp(Cam.FieldOfView-1.2,10,120) end; if FC_UI_Btns.zoomOut then Cam.FieldOfView=math.clamp(Cam.FieldOfView+1.2,10,120) end; FC.pos=FC.pos+(I_CamVel+Vector3.new(0,heightVelocity,0))*sdt; Cam.CFrame=CFrame.new(FC.pos)*CFrame.Angles(0,math.rad(FC.yawDeg),0)*CFrame.Angles(math.rad(FC.pitchDeg),0,0)*CFrame.Angles(0,0,math.rad(FC.rollDeg)) end) end
local function stopFreecamLoop() RS:UnbindFromRenderStep("XKIDFreecam") end
local function fullCleanupFreecam() stopFreecamLoop(); stopFreecamCapture(); local h=getHum(); local r=getRoot(); if h then h.WalkSpeed=FC.savedWalkSpeed; h.UseJumpPower=true; h.JumpPower=FC.savedJumpPower end; if FC.wasAnchored and r then r.Anchored=false; FC.wasAnchored=false end; Cam.CameraType=Enum.CameraType.Custom; Cam.FieldOfView=FC.origFov; if getgenv()._XKID_FCUI then getgenv()._XKID_FCUI.Enabled=false end; for k in pairs(FC_UI_Btns) do FC_UI_Btns[k]=false end; FC_UI_Hidden=false; eyeBtn.Text="👁"; for _,b in ipairs(fcButtons) do b.Visible=true end end

-- SELF-SPECTATE (diringkas)
local SS=State.SelfSpec
local ssTM,ssPinch,ssPinchD,ssPan,ssConns=nil,{},nil,Vector2.zero,{}
local function startSSGesture() ssConns={}; table.insert(ssConns,UIS.InputBegan:Connect(function(inp,gp) if gp or not SS.active or inp.UserInputType~=Enum.UserInputType.Touch then return end; table.insert(ssPinch,inp); ssTM=#ssPinch==1 and inp or nil end)); table.insert(ssConns,UIS.InputChanged:Connect(function(inp) if not SS.active or inp.UserInputType~=Enum.UserInputType.Touch then return end; if #ssPinch==1 and inp==ssTM then ssPan=ssPan+Vector2.new(inp.Delta.X,inp.Delta.Y) elseif #ssPinch>=2 then local d=(ssPinch[1].Position-ssPinch[2].Position).Magnitude; if ssPinchD then local diff=d-ssPinchD; Cam.FieldOfView=math.clamp(Cam.FieldOfView-diff*0.15,10,120); SS.radius=math.clamp(SS.radius-diff*0.03,3,30) end; ssPinchD=d end end)); table.insert(ssConns,UIS.InputEnded:Connect(function(inp) if inp.UserInputType~=Enum.UserInputType.Touch then return end; for i,v in ipairs(ssPinch) do if v==inp then table.remove(ssPinch,i); break end end; ssPinchD=nil; ssTM=#ssPinch==1 and ssPinch[1] or nil end)) end
local function stopSSGesture() for _,c in ipairs(ssConns) do c:Disconnect() end; ssConns={}; ssTM=nil; ssPinch={}; ssPinchD=nil; ssPan=Vector2.zero end
local function startSelfSpecLoop() RS:UnbindFromRenderStep("XKIDSelfSpec"); RS:BindToRenderStep("XKIDSelfSpec",Enum.RenderPriority.Camera.Value+1,function() if not SS.active then return end; pcall(function() local tc=LP.Character; local thrp=getCharRoot(tc); if not thrp then return end; Cam.CameraType=Enum.CameraType.Scriptable; local pan,sens=ssPan,onMobile and 0.2 or 0.3; ssPan=Vector2.zero; if SS.mode=="First Person" then local head=tc:FindFirstChild("Head"); local o=head and head.Position or thrp.Position+Vector3.new(0,1.5,0); SS.fpYaw=SS.fpYaw-pan.X*sens; SS.fpPitch=math.clamp(SS.fpPitch-pan.Y*sens,-85,85); Cam.CFrame=CFrame.new(o)*CFrame.Angles(0,math.rad(SS.fpYaw),0)*CFrame.Angles(math.rad(SS.fpPitch),0,0) else if #ssPinch==0 and pan.Magnitude<0.01 then local dt=0.016; if SS.mode=="Slow Orbit" then SS.orbitYaw=SS.orbitYaw+dt*25*SS.speed elseif SS.mode=="Vertical Swing" then SS.orbitPitch=20+math.sin(tick()*SS.speed*1.5)*40; SS.orbitYaw=SS.orbitYaw+dt*10*SS.speed elseif SS.mode=="Figure 8" then SS.orbitYaw=math.sin(tick()*SS.speed*0.8)*80; SS.orbitPitch=20+math.sin(tick()*SS.speed*1.2)*35 elseif SS.mode=="Cinematic Drift" then SS.orbitYaw=SS.orbitYaw+dt*15*SS.speed; SS.orbitPitch=20+math.sin(tick()*SS.speed*0.7)*15 elseif SS.mode=="Top Down" then SS.orbitPitch=-75; SS.orbitYaw=SS.orbitYaw+dt*8*SS.speed end end; SS.orbitYaw=SS.orbitYaw+pan.X*sens; SS.orbitPitch=math.clamp(SS.orbitPitch+pan.Y*sens,-75,75); local h=(SS.mode=="Top Down") and 15 or (SS.height or 3); Cam.CFrame=CFrame.new((CFrame.new(thrp.Position+Vector3.new(0,h,0))*CFrame.Angles(0,math.rad(-SS.orbitYaw),0)*CFrame.Angles(math.rad(-SS.orbitPitch),0,0)*CFrame.new(0,0,SS.radius)).Position,thrp.Position+Vector3.new(0,h,0)) end end) end) end
local function stopSelfSpecLoop() RS:UnbindFromRenderStep("XKIDSelfSpec"); Cam.CameraType=Enum.CameraType.Custom; Cam.FieldOfView=SS.origFov; SS.active=false; SS.orbitYaw=0; SS.orbitPitch=20; SS.fpYaw=0; SS.fpPitch=0; SS.radius=8; SS.height=3; ssPan=Vector2.zero end
local function toggleSelfSpec(v) if v then if FC.active then fullCleanupFreecam() end; if State.Fly.active then stopFlyCapture() end; if Spec and Spec.active then stopSpecCapture() end; if Teleport.clickConn then Teleport.clickConn:Disconnect(); Teleport.clickConn=nil end; SS.active=true; SS.origFov=Cam.FieldOfView; SS.orbitYaw=0; SS.orbitPitch=20; SS.fpYaw=0; SS.fpPitch=0; SS.radius=SS.radius or 8; SS.height=SS.height or 3; startSSGesture(); startSelfSpecLoop(); notify("Self-Spectate","ON — "..(SS.mode or "Manual"),2,"camera") else SS.active=false; stopSSGesture(); stopSelfSpecLoop(); notify("Self-Spectate","OFF",1.5,"camera") end end

-- SPECTATE (diringkas)
local Spec={active=false,target=nil,mode="third",dist=8,origFov=70,orbitYaw=0,orbitPitch=0,fpYaw=0,fpPitch=0,isSelf=false}
local specTM,specPinch,specPinchD,specPan,specConns=nil,{},nil,Vector2.zero,{}
local function startSpecCapture() table.insert(specConns,UIS.InputBegan:Connect(function(inp,gp) if gp or not Spec.active or inp.UserInputType~=Enum.UserInputType.Touch then return end; table.insert(specPinch,inp); specTM=#specPinch==1 and inp or nil end)); table.insert(specConns,UIS.InputChanged:Connect(function(inp) if not Spec.active or inp.UserInputType~=Enum.UserInputType.Touch then return end; if #specPinch==1 and inp==specTM then specPan=specPan+Vector2.new(inp.Delta.X,inp.Delta.Y) elseif #specPinch>=2 then local d=(specPinch[1].Position-specPinch[2].Position).Magnitude; if specPinchD then local diff=d-specPinchD; Cam.FieldOfView=math.clamp(Cam.FieldOfView-diff*0.15,10,120); if Spec.mode=="third" then Spec.dist=math.clamp(Spec.dist-diff*0.03,3,30) end end; specPinchD=d end end)); table.insert(specConns,UIS.InputEnded:Connect(function(inp) if inp.UserInputType~=Enum.UserInputType.Touch then return end; for i,v in ipairs(specPinch) do if v==inp then table.remove(specPinch,i); break end end; specPinchD=nil; specTM=#specPinch==1 and specPinch[1] or nil end)) end
local function stopSpecCapture() for _,c in ipairs(specConns) do c:Disconnect() end; specConns={}; specTM=nil; specPinch={}; specPinchD=nil; specPan=Vector2.zero end
local function startSpecLoop() RS:BindToRenderStep("XKIDSpec",Enum.RenderPriority.Camera.Value+1,function() if not Spec.active then return end; pcall(function() local tc,thrp; if Spec.isSelf then tc=LP.Character; thrp=getCharRoot(tc) else if not Spec.target or not Spec.target.Character then Spec.active=false; stopSpecLoop(); stopSpecCapture(); Cam.CameraType=Enum.CameraType.Custom; Cam.FieldOfView=Spec.origFov; return end; tc=Spec.target.Character; thrp=tc:FindFirstChild("HumanoidRootPart") end; if not thrp then if not Spec.isSelf then Spec.active=false; stopSpecLoop(); stopSpecCapture(); Cam.CameraType=Enum.CameraType.Custom; Cam.FieldOfView=Spec.origFov end; return end; Cam.CameraType=Enum.CameraType.Scriptable; local pan,sens=specPan,0.3; specPan=Vector2.zero; if Spec.mode=="third" then Spec.orbitYaw=Spec.orbitYaw+pan.X*sens; Spec.orbitPitch=math.clamp(Spec.orbitPitch+pan.Y*sens,-75,75); Cam.CFrame=CFrame.new((CFrame.new(thrp.Position)*CFrame.Angles(0,math.rad(-Spec.orbitYaw),0)*CFrame.Angles(math.rad(-Spec.orbitPitch),0,0)*CFrame.new(0,0,Spec.dist)).Position,thrp.Position+Vector3.new(0,1,0)) else local head=tc:FindFirstChild("Head"); local o=head and head.Position or thrp.Position+Vector3.new(0,1.5,0); Spec.fpYaw=Spec.fpYaw-pan.X*sens; Spec.fpPitch=math.clamp(Spec.fpPitch-pan.Y*sens,-85,85); Cam.CFrame=CFrame.new(o)*CFrame.Angles(0,math.rad(Spec.fpYaw),0)*CFrame.Angles(math.rad(Spec.fpPitch),0,0) end end) end) end
local function stopSpecLoop() RS:UnbindFromRenderStep("XKIDSpec") end

-- AUTO LIKE
local function getLikeRemotes() local r=ReplicatedStorage:FindFirstChild("Remotes"); if not r then return nil,nil end; return r:FindFirstChild("GetLikeDataRemote"),r:FindFirstChild("LikePlayerEvent") end
local function likeRandomPlayer() local _,lp=getLikeRemotes(); if not lp then return false,"Remote not found" end; local r=getRoot(); local t={}; for _,p in pairs(Players:GetPlayers()) do if p~=LP then if State.AutoLike.radius>0 and r then local pr=p.Character and p.Character:FindFirstChild("HumanoidRootPart"); if pr then local d=(pr.Position-r.Position).Magnitude; if d<=State.AutoLike.radius then table.insert(t,p) end end else table.insert(t,p) end end end; if #t==0 then return false,"No players in range" end; local target; if #t==1 then target=t[1] else repeat target=t[math.random(1,#t)] until target~=State.AutoLike.lastTarget or #t<=1 end; State.AutoLike.lastTarget=target; local s=pcall(function() lp:FireServer(target) end); if s then State.AutoLike.count=State.AutoLike.count+1; return true,target.DisplayName end; return false,"Failed" end
local function startAutoLike() if State.AutoLike.active then return end; State.AutoLike.active=true; State.AutoLike.thread=task.spawn(function() while State.AutoLike.active and getgenv()._XKID_RUNNING do local o,r=likeRandomPlayer(); if o then notify("Auto Like",r.." | Total: "..State.AutoLike.count,1.5,"heart") end; local cd=math.random(State.AutoLike.minCD*10,State.AutoLike.maxCD*10)/10; task.wait(cd) end; State.AutoLike.thread=nil end); notify("Auto Like","ON",2,"heart") end
local function stopAutoLike() State.AutoLike.active=false; if State.AutoLike.thread then task.cancel(State.AutoLike.thread); State.AutoLike.thread=nil end; notify("Auto Like","OFF",1.5,"heart") end

-- HARD FLING
local hardFlingConn,hardFlingRampConn,hardFlingBAV=nil,nil,nil
local function startHardFling() if State.HardFling.active then return end; State.HardFling.active=true; State.Move.ncp=true; State.HardFling.currentPower=0; State.HardFling.rampUpActive=true; local r=getRoot(); if r then hardFlingBAV=Instance.new("BodyAngularVelocity",r); hardFlingBAV.MaxTorque=Vector3.new(9e9,9e9,9e9); hardFlingBAV.P=100000 end; local rampStart=tick(); hardFlingRampConn=TrackC(RS.Heartbeat:Connect(function() if not State.HardFling.rampUpActive then return end; local t=math.clamp((tick()-rampStart)/2,0,1); State.HardFling.currentPower=State.HardFling.power*t; if t>=1 then State.HardFling.currentPower=State.HardFling.power; State.HardFling.rampUpActive=false end end)); hardFlingConn=TrackC(RS.Heartbeat:Connect(function() if not State.HardFling.active then return end; local r2=getRoot(); if not r2 then return end; if State.HardFling.mode=="Spin" then if hardFlingBAV and hardFlingBAV.Parent then hardFlingBAV.AngularVelocity=Vector3.new(0,State.HardFling.currentPower,0) end elseif State.HardFling.mode=="Shake" then if hardFlingBAV and hardFlingBAV.Parent then local sx=(math.random()-0.5)*State.HardFling.currentPower*0.5; local sy=(math.random()-0.5)*State.HardFling.currentPower*0.3; local sz=(math.random()-0.5)*State.HardFling.currentPower*0.5; hardFlingBAV.AngularVelocity=Vector3.new(sx,sy,sz) end end; if LP.Character then for _,p in pairs(LP.Character:GetDescendants()) do if p:IsA("BasePart") then p.CanCollide=false end end end end)); notify("Hard Fling","ON — "..State.HardFling.mode,2,"zap") end
local function stopHardFling() State.HardFling.active=false; State.HardFling.rampUpActive=false; State.HardFling.currentPower=0; if hardFlingConn then hardFlingConn:Disconnect(); hardFlingConn=nil end; if hardFlingRampConn then hardFlingRampConn:Disconnect(); hardFlingRampConn=nil end; if hardFlingBAV then hardFlingBAV:Destroy(); hardFlingBAV=nil end; local r=getRoot(); if r then pcall(function() r.AssemblyAngularVelocity=Vector3.zero; r.AssemblyLinearVelocity=Vector3.zero end) end; if LP.Character then for _,p in pairs(LP.Character:GetDescendants()) do if p:IsA("BasePart") then p.CanCollide=true end end end; notify("Hard Fling","OFF",1.5,"zap") end

-- FILTER PRESETS (TABEL - RAPI)
local FILTERS = {
  Default = {tint=Color3.new(1,1,1),sat=0,con=0,bri=0,bloomI=0,bloomS=24,time=14,exp=0,dofI=0,dofD=50,lightB=1,shadow=true},
  Mendung_HD = {tint=Color3.fromRGB(180,185,200),sat=-0.3,con=0.1,bri=-0.15,bloomI=0.05,bloomS=24,time=10,exp=0,lightB=0.7,shadow=true},
  Cool_Blue_HD = {tint=Color3.fromRGB(180,200,255),sat=0.1,con=0.15,bri=0.05,bloomI=0.2,bloomS=24,time=12,exp=0,lightB=1.2,shadow=true},
  Soft_Fade_HD = {tint=Color3.fromRGB(255,240,235),sat=-0.1,con=-0.05,bri=0.1,bloomI=0.4,bloomS=35,time=15,exp=0,lightB=1.3,shadow=true},
  Adaptif_Langit_HD = {tint=Color3.new(1,1,1),sat=0.15,con=0.2,bri=0.05,bloomI=0.15,bloomS=24,time=13,exp=0,lightB=1.5,shadow=true},
  Edgy_HD = {tint=Color3.fromRGB(200,195,210),sat=-0.5,con=0.4,bri=-0.1,bloomI=0.3,bloomS=20,time=8,exp=0,lightB=0.8,shadow=true},
  Full_Bright_HD = {tint=Color3.new(1,1,1),sat=0,con=0,bri=0,bloomI=0,bloomS=24,time=12,exp=0,lightB=3,shadow=false,ambient=Color3.new(1,1,1),outdoor=Color3.new(1,1,1)},
  Soft_Pastel_HD = {tint=Color3.fromRGB(255,240,245),sat=-0.05,con=0.05,bri=0,bloomI=0.3,bloomS=24,time=8,exp=0,lightB=1,shadow=true},
  Cinematic_Soft = {tint=Color3.new(1,1,1),sat=0.1,con=0.15,bri=0.05,bloomI=0.2,bloomS=24,time=17,exp=0,lightB=1,shadow=true},
  Ultra_HD = {tint=Color3.new(1,1,1),sat=0.2,con=0.3,bri=0,bloomI=0.2,bloomS=24,time=14,exp=0,lightB=1,shadow=true},
  Realistic = {tint=Color3.new(1,1,1),sat=0.1,con=0.2,bri=0,bloomI=0.15,bloomS=24,time=15,exp=0,lightB=1,shadow=true},
  Night_HD = {tint=Color3.fromRGB(200,200,255),sat=0.1,con=0.2,bri=0,bloomI=0.15,bloomS=24,time=1,exp=0,lightB=1,shadow=true},
  Senja = {tint=Color3.fromRGB(255,180,120),sat=0.2,con=0.1,bri=0.05,bloomI=0.5,bloomS=40,time=17.5,exp=0,lightB=1,shadow=true},
  Cinematic_Film = {tint=Color3.fromRGB(200,210,230),sat=-0.15,con=0.25,bri=-0.05,bloomI=0.15,bloomS=20,time=16,exp=0,lightB=1,shadow=true},
  Golden_Hour = {tint=Color3.fromRGB(255,200,100),sat=0.1,con=0.15,bri=0.1,bloomI=0.4,bloomS=35,time=17.5,exp=0,lightB=1,shadow=true},
  Moody_Blue = {tint=Color3.fromRGB(150,170,255),sat=0.05,con=0.2,bri=-0.1,bloomI=0.1,bloomS=24,time=2,exp=0,lightB=1,shadow=true},
}
local function resetFilterOnly() for _,v in pairs(Lighting:GetChildren()) do if v.Name=="_XKID_FILTER" then v:Destroy() end end end
local function resetDOFOnly() for _,v in pairs(Lighting:GetChildren()) do if v.Name=="_XKID_DOF" then v:Destroy() end end end
local function applyCustomFilter() resetFilterOnly(); Lighting.Brightness=originalLighting.Brightness; Lighting.Ambient=originalLighting.Ambient; Lighting.OutdoorAmbient=originalLighting.OutdoorAmbient; Lighting.GlobalShadows=originalLighting.GlobalShadows; Lighting.ExposureCompensation=State.CustomFilter.exposure; local cc=Instance.new("ColorCorrectionEffect",Lighting); cc.Name="_XKID_FILTER"; cc.TintColor=Color3.fromRGB(State.CustomFilter.tintR,State.CustomFilter.tintG,State.CustomFilter.tintB); cc.Saturation=State.CustomFilter.saturation; cc.Contrast=State.CustomFilter.contrast; cc.Brightness=State.CustomFilter.brightness; local bloom=Instance.new("BloomEffect",Lighting); bloom.Name="_XKID_FILTER"; bloom.Intensity=State.CustomFilter.bloomIntensity; bloom.Size=State.CustomFilter.bloomSize; Lighting.ClockTime=State.CustomFilter.clockTime; resetDOFOnly(); if State.CustomFilter.dofIntensity>0 then local dof=Instance.new("DepthOfFieldEffect",Lighting); dof.Name="_XKID_DOF"; dof.FarIntensity=State.CustomFilter.dofIntensity; dof.FocusDistance=State.CustomFilter.dofDistance end end
local function applyFilter(f)
  resetFilterOnly(); resetDOFOnly(); Lighting.ClockTime=originalLighting.ClockTime; Lighting.Brightness=originalLighting.Brightness; Lighting.Ambient=originalLighting.Ambient; Lighting.OutdoorAmbient=originalLighting.OutdoorAmbient; Lighting.GlobalShadows=originalLighting.GlobalShadows; Lighting.ExposureCompensation=originalLighting.ExposureCompensation
  if f=="Default" then for k,v in pairs(FILTERS.Default) do if State.CustomFilter[k]~=nil then State.CustomFilter[k]=v end end; notify("Visuals","Default",1.5,"palette") return end
  if f=="Custom" then applyCustomFilter(); notify("Visuals","Custom FX",1.5,"palette") return end
  local key=f:gsub(" ","_"):gsub(" HD","_HD"); local p=FILTERS[key]
  if p then
    Lighting.ClockTime=p.time or 14; Lighting.Brightness=p.lightB or 1; Lighting.ExposureCompensation=p.exp or 0; Lighting.GlobalShadows=p.shadow~=false
    if p.ambient then Lighting.Ambient=p.ambient end; if p.outdoor then Lighting.OutdoorAmbient=p.outdoor end
    local cc=Instance.new("ColorCorrectionEffect",Lighting); cc.Name="_XKID_FILTER"; cc.TintColor=p.tint; cc.Saturation=p.sat or 0; cc.Contrast=p.con or 0; cc.Brightness=p.bri or 0
    local bloom=Instance.new("BloomEffect",Lighting); bloom.Name="_XKID_FILTER"; bloom.Intensity=p.bloomI or 0; bloom.Size=p.bloomS or 24
    if p.dofI and p.dofI>0 then local dof=Instance.new("DepthOfFieldEffect",Lighting); dof.Name="_XKID_DOF"; dof.FarIntensity=p.dofI; dof.FocusDistance=p.dofD or 50 end
    State.CustomFilter.tintR=p.tint.R*255; State.CustomFilter.tintG=p.tint.G*255; State.CustomFilter.tintB=p.tint.B*255; State.CustomFilter.saturation=p.sat or 0; State.CustomFilter.contrast=p.con or 0; State.CustomFilter.brightness=p.bri or 0; State.CustomFilter.exposure=p.exp or 0; State.CustomFilter.bloomIntensity=p.bloomI or 0; State.CustomFilter.bloomSize=p.bloomS or 24; State.CustomFilter.clockTime=p.time or 14; State.CustomFilter.dofIntensity=p.dofI or 0; State.CustomFilter.dofDistance=p.dofD or 50
    notify("Visuals",f,2,"palette")
  end
end

-- MAIN WINDOW UI
local Window = WindUI:CreateWindow({Title="XKID HUB",Icon="bluetooth",Author="v"..CURRENT_VERSION,Folder="XKIDHub",Size=UDim2.fromOffset(360,320),Transparent=true,Theme="Crimson",SideBarWidth=160,User={Enabled=true,Anonymous=false},Topbar={Height=40,ButtonsType="Default"}})
pcall(function() WindUI:SetFont("rbxassetid://12187376357") end); pcall(function() WindUI:SetNotificationLower(true) end); pcall(function() Window.User:SetDisplayName(LP.DisplayName); Window.User:SetUsername("@"..LP.Name) end)
Window:EditOpenButton({Title="WTF.XKID",Icon="wifi",CornerRadius=UDim.new(1,0),StrokeThickness=2,StrokeColor=Color3.fromRGB(255,70,120),Enabled=true,Draggable=true,Scale=0.72})
local FpsTag = Window:Tag({Title="FPS: -- | Ping: --",Color=Color3.fromRGB(255,215,0),Icon="github"})
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(1); if FpsTag and FpsTag.SetTitle then FpsTag:SetTitle("FPS: "..sharedFPS.." | Ping: "..sharedPing.."ms") end end end)

local TabInfo = Window:Tab({Title="Informasi",Icon="activity"})
local TabChar = Window:Tab({Title="Character",Icon="fingerprint"})
local TabTP   = Window:Tab({Title="Teleport",Icon="map-pin-x-inside"})
local TabSpec = Window:Tab({Title="Spectator",Icon="cctv"})
local TabCine = Window:Tab({Title="Cinematic",Icon="aperture"})
local TabVis  = Window:Tab({Title="Visuals",Icon="moon-star"})
local TabESP  = Window:Tab({Title="ESP",Icon="scan-search"})
local TabLog  = Window:Tab({Title="Logger",Icon="square-terminal"})
local TabProt = Window:Tab({Title="Protection",Icon="shield-half"})
local TabSet  = Window:Tab({Title="Settings",Icon="panels-top-left"})

-- TAB INFO
local function getExecutor() pcall(function() local e=identifyexecutor(); if e and e~="" then return e end end); pcall(function() local e=getexecutorname(); if e and e~="" then return e end end); return "Unknown" end
local execName, accountAge, avatarImage = getExecutor(), LP.AccountAge.." days", "rbxthumb://type=AvatarHeadShot&id="..LP.UserId.."&w=420&h=420"
local afkStatusParagraph = TabInfo:Paragraph({Title="YooWssp!!, "..LP.DisplayName,Desc="Executor: "..execName.."\nAccount Age: "..accountAge.."\nUserID: "..LP.UserId.."\nStatus: "..(LP.MembershipType==Enum.MembershipType.Premium and "Premium" or "Normal").."\nAnti AFK: ON ✅",Image=avatarImage,ImageSize=80})
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(1); pcall(function() afkStatusParagraph:SetDesc("Executor: "..execName.."\nAccount Age: "..accountAge.."\nUserID: "..LP.UserId.."\nStatus: "..(LP.MembershipType==Enum.MembershipType.Premium and "Premium" or "Normal").."\nAnti AFK: "..(State.Security.afkActive and "ON ✅" or "OFF ❌")) end) end end)
local infoParagraph = TabInfo:Paragraph({Title="💀 "..LP.DisplayName.." v"..CURRENT_VERSION.."\n⚡ "..makeBar(sharedFPS,120,10).." "..sharedFPS.." FPS\n📡 "..makeBar(math.max(1,200-sharedPing),200,10).." "..sharedPing.."ms\n🕐 "..makeBar(os.difftime(os.time(),START_TIME)%3600,3600,10).." "..formatTime(os.difftime(os.time(),START_TIME)),Desc="👤 "..LP.DisplayName.."\n📱 "..(onMobile and "Mobile" or "PC").." | 🚀 "..execName.."\n\n🎮 "..(cachedMapName or "Loading...").."\n👥 "..makeBar(#Players:GetPlayers(),Players.MaxPlayers,10).." "..#Players:GetPlayers().."/"..Players.MaxPlayers.." Players\n\n🌐 discord.gg/bzumc2u96"})
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(1); pcall(function() infoParagraph:SetTitle("💀 "..LP.DisplayName.." v"..CURRENT_VERSION.."\n⚡ "..makeBar(sharedFPS,120,10).." "..sharedFPS.." FPS\n📡 "..makeBar(math.max(1,200-sharedPing),200,10).." "..sharedPing.."ms\n🕐 "..makeBar(os.difftime(os.time(),START_TIME)%3600,3600,10).." "..formatTime(os.difftime(os.time(),START_TIME))) end) end end)
TabInfo:Section({Title="🔗 Discord",Icon="message-circle",Box=true}):Button({Title="Copy Discord Link",Desc="discord.gg/bzumc2u96",Callback=function() pcall(function() setclipboard("https://discord.gg/bzumc2u96") end); notify("System","Link copied",2,"copy") end})

-- TAB CHARACTER
TabChar:Button({Title="Refresh Character 🔄",Desc="Reload character like /re — no gamepass",Callback=refreshCharacter})
local secMov = TabChar:Section({Title="Movement",Icon="activity",Box=true})
secMov:Slider({Title="Walk Speed",Step=1,Value={Min=16,Max=500,Default=16},Callback=function(v) State.Move.ws=v; if getHum() then getHum().WalkSpeed=v end end})
secMov:Slider({Title="Jump Power",Step=1,Value={Min=50,Max=500,Default=50},Callback=function(v) State.Move.jp=v; local h=getHum(); if h then h.UseJumpPower=true; h.JumpPower=v end end})
secMov:Toggle({Title="Infinite Jump",Default=false,Callback=function(v) if v then State.Move.infJ=TrackC(UIS.JumpRequest:Connect(function() if getHum() then getHum():ChangeState(Enum.HumanoidStateType.Jumping) end end)) else if State.Move.infJ then State.Move.infJ:Disconnect(); State.Move.infJ=nil end end; notify("Infinite Jump",v and "ON" or "OFF",1.5,"arrow-big-up") end})
local secAutoWalk = TabChar:Section({Title="Auto Walk",Icon="play",Box=true})
secAutoWalk:Toggle({Title="Auto Walk",Default=false,Callback=function(v) if v then startAutoWalk() else stopAutoWalk() end end})
secAutoWalk:Slider({Title="Walk Speed",Step=1,Value={Min=1,Max=100,Default=16},Callback=function(v) State.Move.autoWalkSpeed=v; if State.Move.autoWalk then local h=getHum(); if h then h.WalkSpeed=v end end end})
secAutoWalk:Paragraph({Title="Info",Desc="Character walks forward automatically\nMove manually to override"})
local secAbi = TabChar:Section({Title="Abilities",Icon="zap",Box=true})
secAbi:Toggle({Title="Fly",Default=false,Callback=function(v) toggleFly(v) end})
secAbi:Slider({Title="Fly Speed",Step=1,Value={Min=10,Max=300,Default=60},Callback=function(v) State.Move.flyS=v end})
local noclipConn=nil
secAbi:Toggle({Title="NoClip",Default=false,Callback=function(v) State.Move.ncp=v; if v then if not noclipConn then noclipConn=TrackC(RS.Heartbeat:Connect(function() if not State.Move.ncp then return end; if LP.Character then for _,p in pairs(LP.Character:GetDescendants()) do if p:IsA("BasePart") then p.CanCollide=false end end end end)) end else if noclipConn then noclipConn:Disconnect(); noclipConn=nil end; if LP.Character then for _,p in pairs(LP.Character:GetDescendants()) do if p:IsA("BasePart") then p.CanCollide=true end end end end; notify("NoClip",v and "ON" or "OFF",1.5,"ghost") end})
local secFling = TabChar:Section({Title="Hard Fling (Safe)",Icon="rotate-cw",Box=true})
secFling:Toggle({Title="Hard Fling",Default=false,Callback=function(v) if v then startHardFling() else stopHardFling() end end})
secFling:Dropdown({Title="Fling Mode",Values={"Spin","Shake"},Default="Spin",Callback=function(v) State.HardFling.mode=v; notify("Fling Mode",v,1.5,"rotate-cw") end})
secFling:Slider({Title="Fling Power",Step=500,Value={Min=1000,Max=50000,Default=10000},Callback=function(v) State.HardFling.power=v end})

-- TAB TELEPORT
local secDirTP = TabTP:Section({Title="Direct Teleport",Icon="map-pin",Box=true})
secDirTP:Toggle({Title="Smart TP",Desc="Equip tool → tap to toggle mode → tap to TP",Default=false,Callback=toggleSmartTP})
local secTargetTP = TabTP:Section({Title="Target Teleport",Icon="crosshair",Box=true})
local tpTarget=""
secTargetTP:Input({Title="Search Player",Placeholder="Type name...",Callback=function(v) tpTarget=v end})
secTargetTP:Button({Title="Execute TP",Desc="Teleport to target",Callback=function() pcall(function() if tpTarget=="" then notify("Teleport","Input target!",2,"circle-alert"); return end; local t=nil; for _,p in pairs(Players:GetPlayers()) do if p~=LP and (string.find(string.lower(p.Name),string.lower(tpTarget)) or string.find(string.lower(p.DisplayName),string.lower(tpTarget))) then t=p; break end end; if not t or not t.Parent or not t.Character then notify("Teleport","Invalid Target",2,"circle-alert"); return end; local thrp=getCharRoot(t.Character); local mhrp=getRoot(); if not thrp or not mhrp then return end; mhrp.CFrame=thrp.CFrame*CFrame.new(0,0,3)+Vector3.new(0,2,0); notify("Teleport",t.DisplayName,2,"map-pin") end) end})
secTargetTP:Dropdown({Title="Player List",Values=getDisplayNames(),Callback=function(v) tpTarget=tostring(v) end})
secTargetTP:Button({Title="Refresh List",Callback=function() notify("Teleport","List refreshed",1.5,"map-pin") end})
local secCache = TabTP:Section({Title="Coordinates Cache",Icon="save",Box=true})
local SavedLocs={}
for i=1,3 do local idx=i; local hc=secCache:HStack({Columns=2}); hc:Button({Title="💾 Save "..idx,Callback=function() local r=getRoot(); if not r then return end; SavedLocs[idx]=r.CFrame; notify("Slot "..idx,"Saved",1.5,"save") end}); hc:Button({Title="📍 Load "..idx,Callback=function() if not SavedLocs[idx] then notify("Slot "..idx,"Empty",1.5,"save"); return end; local r=getRoot(); if not r then return end; r.CFrame=SavedLocs[idx]; notify("Slot "..idx,"Loaded",1.5,"map-pin") end}) end

-- TAB SPECTATOR
local secZoom = TabSpec:Section({Title="Zoom Override",Icon="zoom-in",Box=true})
secZoom:Toggle({Title="Max Zoom Out",Default=false,Callback=function(v) pcall(function() LP.CameraMaxZoomDistance=v and 1e5 or 400 end); notify("Zoom",v and "Max" or "Default",1.5,"zoom-in") end})
local secSP = TabSpec:Section({Title="Spectator Mode",Icon="eye",Box=true})
secSP:Dropdown({Title="Select Target",Values=getDisplayNamesWithSelf(),Callback=function(v) local s=tostring(v); if s=="[Self]" then Spec.target=LP; Spec.isSelf=true; Spec.orbitYaw=0; Spec.orbitPitch=20; Spec.fpYaw=0; notify("Spectator","Self",1.5,"eye") else local p=findPlayerByDisplay(s); if p then Spec.target=p; Spec.isSelf=false; if p.Character and p.Character:FindFirstChild("HumanoidRootPart") then local _,ry,_=p.Character.HumanoidRootPart.CFrame:ToEulerAnglesYXZ(); Spec.orbitYaw=math.deg(ry); Spec.orbitPitch=20; Spec.fpYaw=math.deg(ry) end; notify("Spectator",p.DisplayName,1.5,"eye") end end end})
secSP:Button({Title="Refresh Target List",Callback=function() notify("Spectator","List refreshed",1.5,"eye") end})
secSP:Toggle({Title="Enable Spectate",Default=false,Callback=function(v) if SS.active then toggleSelfSpec(false) end; Spec.active=v; if v then if not Spec.target or not Spec.target.Character then if Spec.isSelf and LP.Character then else Spec.active=false; notify("Error","No target",2,"circle-alert"); return end end; Spec.origFov=Cam.FieldOfView; startSpecCapture(); startSpecLoop(); notify("Spectator","ON",2,"eye") else stopSpecLoop(); stopSpecCapture(); Cam.CameraType=Enum.CameraType.Custom; Cam.FieldOfView=Spec.origFov; notify("Spectator","OFF",1.5,"eye") end end})
secSP:Toggle({Title="First Person View",Default=false,Callback=function(v) Spec.mode=v and "first" or "third"; notify("Spectator",v and "First Person" or "Third Person",1.5,"eye") end})
secSP:Slider({Title="Distance",Step=1,Value={Min=3,Max=30,Default=8},Callback=function(v) Spec.dist=v end})

-- TAB CINEMATIC
local secSelfSpec = TabCine:Section({Title="🎥 Self-Spectate",Icon="camera",Box=true})
secSelfSpec:Toggle({Title="Enable Self-Spectate",Desc="1-finger orbit | 2-finger zoom | Mouse right-drag",Default=false,Callback=toggleSelfSpec})
secSelfSpec:Dropdown({Title="Preset Mode",Values={"Manual","Slow Orbit","Vertical Swing","Figure 8","Cinematic Drift","Top Down","First Person"},Default="Manual",Callback=function(v) SS.mode=v; notify("Self-Spec","Mode: "..v,1.5,"camera") end})
secSelfSpec:Slider({Title="Distance / Radius",Step=0.5,Value={Min=3,Max=30,Default=8},Callback=function(v) SS.radius=v; SS.dist=v end})
secSelfSpec:Slider({Title="Height",Step=0.5,Value={Min=-10,Max=20,Default=3},Callback=function(v) SS.height=v end})
secSelfSpec:Slider({Title="Speed",Step=0.1,Value={Min=0.1,Max=5,Default=1},Callback=function(v) SS.speed=v end})
local secFC = TabCine:Section({Title="Drone Engine",Icon="video",Box=true})
secFC:Toggle({Title="Enable Freecam",Default=false,Callback=function(v) if v and SS.active then toggleSelfSpec(false) end; FC.active=v; if v then local cf=Cam.CFrame; FC.pos=cf.Position; FC.pitchDeg=0; FC.yawDeg=0; FC.rollDeg=0; I_CamVel=Vector3.zero; I_YawVel=0; I_PitchVel=0; I_RollVel=0; heightVelocity=0; fcJoy=Vector2.zero; local h=getHum(); local r=getRoot(); if h then FC.savedWalkSpeed=h.WalkSpeed; FC.savedJumpPower=h.JumpPower; h.WalkSpeed=0; h.JumpPower=0 end; if r then r.Anchored=true; FC.wasAnchored=true end; FC.origFov=Cam.FieldOfView; startFreecamCapture(); startFreecamLoop(); if getgenv()._XKID_FCUI then getgenv()._XKID_FCUI.Enabled=true end; FC_UI_Hidden=false; eyeBtn.Text="👁"; for _,b in ipairs(fcButtons) do b.Visible=true end; notify("Freecam","ON",2,"video") else fullCleanupFreecam(); notify("Freecam","OFF",1.5,"video") end end})
secFC:Slider({Title="Camera Speed",Step=0.5,Value={Min=1,Max=20,Default=3},Callback=function(v) FC.speed=v end})
secFC:Slider({Title="Sensitivity",Step=0.05,Value={Min=0.1,Max=1,Default=0.25},Callback=function(v) FC.sens=v end})
local secCine = TabCine:Section({Title="Cinematic Mode",Icon="film",Box=true})
secCine:Toggle({Title="Hide All UI",Default=false,Callback=function(v) if getgenv()._XKID_UI_LOADING then return end; if v then State.Cinema.hideUI=true; State.Cinema.cachedGuis={}; for _,g in pairs(LP.PlayerGui:GetChildren()) do if g:IsA("ScreenGui") and g.Enabled then table.insert(State.Cinema.cachedGuis,g); g.Enabled=false end end; pcall(function() StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.All,false) end) else State.Cinema.hideUI=false; for _,g in pairs(State.Cinema.cachedGuis) do if g and g.Parent then g.Enabled=true end end; State.Cinema.cachedGuis={}; pcall(function() StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.All,true) end) end; notify("Cinematic",v and "UI Hidden" or "UI Shown",1.5,"film") end})

-- TAB VISUALS
local secPresets = TabVis:Section({Title="Presets",Icon="palette",Box=true})
secPresets:Dropdown({Title="Select Filter",Values={"Default","Custom","Mendung HD","Cool Blue HD","Soft Fade HD","Adaptif Langit HD","Edgy HD","Full Bright HD","Soft Pastel HD","Cinematic Soft","Ultra HD","Realistic","Night HD","Senja","Cinematic Film","Golden Hour","Moody Blue"},Default="Default",Callback=applyFilter})
local secFX = TabVis:Section({Title="Custom FX",Icon="sliders",Box=true})
secFX:Slider({Title="Tint Red",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v) State.CustomFilter.tintR=v; applyCustomFilter() end})
secFX:Slider({Title="Tint Green",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v) State.CustomFilter.tintG=v; applyCustomFilter() end})
secFX:Slider({Title="Tint Blue",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v) State.CustomFilter.tintB=v; applyCustomFilter() end})
secFX:Slider({Title="Saturation",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v) State.CustomFilter.saturation=v; applyCustomFilter() end})
secFX:Slider({Title="Contrast",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v) State.CustomFilter.contrast=v; applyCustomFilter() end})
secFX:Slider({Title="Brightness",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v) State.CustomFilter.brightness=v; applyCustomFilter() end})
secFX:Slider({Title="Exposure",Step=0.1,Value={Min=-5,Max=5,Default=0},Callback=function(v) State.CustomFilter.exposure=v; applyCustomFilter() end})
secFX:Slider({Title="Bloom Intensity",Step=0.1,Value={Min=0,Max=5,Default=0},Callback=function(v) State.CustomFilter.bloomIntensity=v; applyCustomFilter() end})
secFX:Slider({Title="Bloom Size",Step=1,Value={Min=0,Max=100,Default=24},Callback=function(v) State.CustomFilter.bloomSize=v; applyCustomFilter() end})
secFX:Slider({Title="ClockTime",Step=0.5,Value={Min=0,Max=24,Default=14},Callback=function(v) State.CustomFilter.clockTime=v; applyCustomFilter() end})
secFX:Button({Title="Reset Custom FX",Callback=function() State.CustomFilter.tintR=255; State.CustomFilter.tintG=255; State.CustomFilter.tintB=255; State.CustomFilter.saturation=0; State.CustomFilter.contrast=0; State.CustomFilter.brightness=0; State.CustomFilter.exposure=0; State.CustomFilter.bloomIntensity=0; State.CustomFilter.bloomSize=24; State.CustomFilter.clockTime=14; State.CustomFilter.dofIntensity=0; State.CustomFilter.dofDistance=50; applyCustomFilter(); notify("Visuals","FX Reset",2,"rotate-ccw") end})
local secDOF = TabVis:Section({Title="Depth of Field",Icon="focus",Box=true})
secDOF:Slider({Title="Blur Intensity",Step=0.1,Value={Min=0,Max=1,Default=0},Callback=function(v) State.CustomFilter.dofIntensity=v; applyCustomFilter() end})
secDOF:Slider({Title="Focus Distance",Step=5,Value={Min=1,Max=500,Default=50},Callback=function(v) State.CustomFilter.dofDistance=v; applyCustomFilter() end})

-- TAB ESP
local secDetect = TabESP:Section({Title="Detection System",Icon="radar",Box=true})
secDetect:Toggle({Title="Enable Radar",Default=false,Callback=function(v) State.ESP.active=v; if not v and State.ESP.cache then for _,c in pairs(State.ESP.cache) do pcall(function() if c.texts then c.texts.Visible=false end; if c.tracer then c.tracer.Visible=false end; for _,l in ipairs(c.boxLines) do if l then l.Visible=false end end; if c.hl then c.hl.Enabled=false end end) end end; notify("ESP",v and "ON" or "OFF",1.5,"radar") end})
secDetect:Dropdown({Title="Tracer Origin",Values={"Bottom","Center","Mouse","OFF"},Default="Bottom",Callback=function(v) State.ESP.tracerMode=v; notify("ESP","Tracer: "..v,1.5,"radar") end})
secDetect:Toggle({Title="Highlight Entity",Default=false,Callback=function(v) State.ESP.highlightMode=v; notify("ESP","Highlight "..(v and "ON" or "OFF"),1.5,"radar") end})
secDetect:Slider({Title="Scan Distance",Step=10,Value={Min=50,Max=500,Default=300},Callback=function(v) State.ESP.maxDrawDistance=v end})
local secESPCol = TabESP:Section({Title="Color Config",Icon="palette",Box=true})
secESPCol:Dropdown({Title="Normal Color",Values={"Hijau","Merah","Biru","Kuning","Ungu","Cyan","Orange","Pink","Putih","Hitam"},Default="Hijau",Callback=function(v) if colorMap[v] then State.ESP.tracerColor_N=colorMap[v]; State.ESP.boxColor_N=colorMap[v] end; notify("ESP","Normal: "..v,1.5,"palette") end})
secESPCol:Dropdown({Title="Suspect Color",Values={"Merah","Hijau","Biru","Kuning","Ungu","Cyan","Orange","Pink","Putih","Hitam","Crimson"},Default="Crimson",Callback=function(v) if colorMap[v] then State.ESP.tracerColor_S=colorMap[v]; State.ESP.boxColor_S=colorMap[v] end; notify("ESP","Suspect: "..v,1.5,"palette") end})
secESPCol:Dropdown({Title="Glitch Acc Color",Values={"Orange","Merah","Hijau","Biru","Kuning","Ungu","Cyan","Pink","Putih","Hitam"},Default="Orange",Callback=function(v) if colorMap[v] then State.ESP.tracerColor_G=colorMap[v]; State.ESP.boxColor_G=colorMap[v] end; notify("ESP","Glitch: "..v,1.5,"palette") end})

-- TAB LOGGER
local secChat = TabLog:Section({Title="Chat Logger",Icon="message-square",Box=true})
secChat:Toggle({Title="Enable Logger",Default=false,Callback=function(v) State.Utility.chatLog=v; if not v then pcall(function() chatLogPanel:SetDesc("Logger disabled") end) end; notify("Logger",v and "ON" or "OFF",1.5,"terminal") end})
chatTargetLabel = secChat:Paragraph({Title="Targets",Desc="None"})
chatTargetDrop = secChat:Dropdown({Title="Select Targets",Multi=true,AllowNone=true,Values=getDisplayNames(),Callback=function(s) State.Utility.chatTargets={}; if s and typeof(s)=="table" then for _,n in ipairs(s) do table.insert(State.Utility.chatTargets,tostring(n)) end end; if #State.Utility.chatTargets>0 then pcall(function() chatTargetLabel:SetDesc("Tracking: "..table.concat(State.Utility.chatTargets,", ")) end) else pcall(function() chatTargetLabel:SetDesc("None") end) end end})
secChat:Button({Title="Clear Targets",Callback=function() State.Utility.chatTargets={}; pcall(function() chatTargetLabel:SetDesc("None") end); pcall(function() chatTargetDrop:SetValues({}); task.wait(0.05); chatTargetDrop:SetValues(getDisplayNames()) end); notify("Logger","Targets cleared",1.5,"terminal") end})
secChat:Button({Title="Refresh List",Callback=function() pcall(function() chatTargetDrop:Refresh(getDisplayNames(),true) end); notify("Logger","List refreshed",1.5,"terminal") end})
chatLogPanel = secChat:Paragraph({Title="Console",Desc="Belum ada chat..."})
secChat:Button({Title="Clear Log",Callback=function() State.Utility.chatHistory={}; pcall(function() chatLogPanel:SetDesc("Belum ada chat...") end); notify("Logger","Log cleared",1.5,"terminal") end})
task.spawn(function() local function onChat(sn,msg) if not State.Utility.chatLog or #State.Utility.chatTargets==0 then return end; local cs=sn:lower():match("^%s*(.-)%s*$"); for _,t in ipairs(State.Utility.chatTargets) do local ct=t:lower():match("^%s*(.-)%s*$"); if cs==ct then local e=string.format("[%s] %s: %s",os.date("%H:%M:%S"),sn,msg); table.insert(State.Utility.chatHistory,e); if #State.Utility.chatHistory>50 then table.remove(State.Utility.chatHistory,1) end; notify("Chat",sn..": "..msg,2,"message-circle"); break end end end; if TextChatService.ChatVersion==Enum.ChatVersion.TextChatService then pcall(function() TrackC(TextChatService.MessageReceived:Connect(function(m) if m.TextSource then onChat(m.TextSource.Name,m.Text) end end)) end) end; local function connectLegacy(p) pcall(function() TrackC(p.Chatted:Connect(function(m) onChat(p.DisplayName,m) end)) end) end; for _,p in pairs(Players:GetPlayers()) do if p~=LP then connectLegacy(p) end end; TrackC(Players.PlayerAdded:Connect(function(p) if p~=LP then connectLegacy(p) end end)) end)
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(0.5); if chatLogPanel and State.Utility.chatLog then pcall(function() local t=table.concat(State.Utility.chatHistory,"\n"); if #t>2000 then t=t:sub(-2000) end; if #t==0 then t="Belum ada chat..." end; chatLogPanel:SetDesc(t) end) end end end)

-- TAB PROTECTION
local secProt = TabProt:Section({Title="Protection Protocols",Icon="shield-check",Box=true})
secProt:Toggle({Title="Anti AFK",Default=false,Callback=function(v) if v then startAFK() else stopAFK() end end})
secProt:Button({Title="Stuck Fix",Desc="Get unstuck from walls/ground",Callback=function() local r,h=getRoot(),getHum(); if r then r.Anchored=false; r.CFrame=r.CFrame+Vector3.new(0,3,0) end; if h then h.Sit=false; h:ChangeState(Enum.HumanoidStateType.Jumping) end; notify("Protection","Stuck fix applied",2,"wrench") end})
local secSrv = TabProt:Section({Title="Server Control",Icon="server",Box=true})
secSrv:Button({Title="Force Rejoin",Desc="Rejoin current server",Callback=function() pcall(function() TPService:TeleportToPlaceInstance(game.PlaceId,game.JobId,LP) end); notify("Server","Rejoining...",2,"log-in") end})
secSrv:Button({Title="Server Hop",Desc="Find a new server",Callback=function() pcall(function() local req=(syn and syn.request) or (http and http.request) or http_request or request; if not req then notify("Error","HTTP not supported",2,"circle-alert"); return end; local res=req({Url="https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Desc&limit=100",Method="GET"}); if res.StatusCode==200 then local b=Http:JSONDecode(res.Body); if b and b.data then for _,v in ipairs(b.data) do if v.playing>0 and v.playing<v.maxPlayers and v.id~=game.JobId then TPService:TeleportToPlaceInstance(game.PlaceId,v.id,LP); notify("Server","Hopping...",2,"shuffle"); return end end end end end) end})
local secPerf = TabProt:Section({Title="Performance",Icon="gauge",Box=true})
local gfxMap={[1]="Level01",[2]="Level02",[3]="Level03",[4]="Level04",[5]="Level05",[6]="Level06",[7]="Level07",[8]="Level08",[9]="Level09",[10]="Level10"}
secPerf:Slider({Title="Quality Level",Step=1,Value={Min=1,Max=10,Default=2},Callback=function(v) if gfxMap[v] then pcall(function() settings().Rendering.QualityLevel=Enum.QualityLevel[gfxMap[v]] end) end; notify("Graphics",gfxMap[v],1.5,"gauge") end})
secPerf:Dropdown({Title="FPS Cap",Values={"30","60","120","144","240","Unlimited"},Default="Unlimited",Callback=function(v) if v=="Unlimited" then pcall(function() if setfpscap then setfpscap(9999) end end) else pcall(function() if setfpscap then setfpscap(tonumber(v)) end end) end; notify("Graphics",v.." FPS",1.5,"gauge") end})
local advCache={level=nil,shadows=true,brightness=5,clockTime=14,fogEnd=1e5,mats={},texs={}}
secPerf:Toggle({Title="FPS Boost",Default=false,Callback=function(v) State.Security.antiLag=v; if v then pcall(function() advCache.level=settings().Rendering.QualityLevel end); advCache.shadows=Lighting.GlobalShadows; advCache.brightness=Lighting.Brightness; advCache.clockTime=Lighting.ClockTime; advCache.fogEnd=Lighting.FogEnd; pcall(function() settings().Rendering.QualityLevel=1 end); Lighting.GlobalShadows=false; Lighting.Brightness=1; Lighting.FogEnd=1e5; for _,o in pairs(workspace:GetDescendants()) do if o:IsA("BasePart") then advCache.mats[o]=o.Material; o.Material=Enum.Material.SmoothPlastic elseif o:IsA("Decal") or o:IsA("Texture") or o:IsA("ParticleEmitter") or o:IsA("Trail") then advCache.texs[o]=o.Enabled; o.Enabled=false end end; notify("Performance","FPS Boost ON",2,"zap") else pcall(function() if advCache.level then settings().Rendering.QualityLevel=advCache.level end end); Lighting.GlobalShadows=advCache.shadows; Lighting.Brightness=advCache.brightness; Lighting.ClockTime=advCache.clockTime; Lighting.FogEnd=advCache.fogEnd; for o,m in pairs(advCache.mats) do if o and o.Parent then o.Material=m end end; for o,e in pairs(advCache.texs) do if o and o.Parent then o.Enabled=e end end; advCache.mats={}; advCache.texs={}; notify("Performance","Graphics restored",2,"zap") end end})
local secCam = TabProt:Section({Title="Camera Lock",Icon="lock",Box=true})
secCam:Toggle({Title="Force Shift Lock",Default=false,Callback=function(v) toggleShiftLock(v) end})

-- TAB SETTINGS
local secTheme = TabSet:Section({Title="🎨 Theme",Icon="palette",Box=true})
secTheme:Dropdown({Title="UI Theme",Values={"Dark","Light","Rose","Sky","Emerald","Violet","Red","Amber","Indigo","Midnight","Crimson"},Default="Crimson",Callback=function(v) WindUI:SetTheme(v) end})
local secFile = TabSet:Section({Title="File Management",Icon="folder",Box=true})
local cfgName,currentConfig="XKID_Config","No config"
secFile:Input({Title="Config Name",Value="XKID_Config",Callback=function(v) cfgName=v end})
secFile:Button({Title="Save Config",Callback=function() pcall(function() if makefolder and writefile then if not isfolder("XKID_HUB") then makefolder("XKID_HUB") end; local d={Move={ws=State.Move.ws,jp=State.Move.jp,flyS=State.Move.flyS,autoWalkSpeed=State.Move.autoWalkSpeed},ESP={tracerMode=State.ESP.tracerMode,maxDrawDistance=State.ESP.maxDrawDistance,highlightMode=State.ESP.highlightMode},Security={shiftLock=State.Security.shiftLock,antiLag=State.Security.antiLag},AutoLike={radius=State.AutoLike.radius,minCD=State.AutoLike.minCD,maxCD=State.AutoLike.maxCD},HardFling={power=State.HardFling.power,mode=State.HardFling.mode},SelfSpec={mode=SS.mode,radius=SS.radius,height=SS.height,speed=SS.speed},CustomFilter={tintR=State.CustomFilter.tintR,tintG=State.CustomFilter.tintG,tintB=State.CustomFilter.tintB,saturation=State.CustomFilter.saturation,contrast=State.CustomFilter.contrast,brightness=State.CustomFilter.brightness,exposure=State.CustomFilter.exposure,bloomIntensity=State.CustomFilter.bloomIntensity,bloomSize=State.CustomFilter.bloomSize,clockTime=State.CustomFilter.clockTime,dofIntensity=State.CustomFilter.dofIntensity,dofDistance=State.CustomFilter.dofDistance}}; writefile("XKID_HUB/"..cfgName..".json",Http:JSONEncode(d)); notify("Config","Saved: "..cfgName,2,"save") end end) end})
local configDrop = secFile:Dropdown({Title="Load Config",Values=getConfigList(),Callback=function(s) currentConfig=s; if s=="No config" then return end; pcall(function() if isfile and readfile and isfile("XKID_HUB/"..s..".json") then local d=Http:JSONDecode(readfile("XKID_HUB/"..s..".json")); if d then if d.Move then State.Move.ws=d.Move.ws or 16; State.Move.jp=d.Move.jp or 50; State.Move.flyS=d.Move.flyS or 60; State.Move.autoWalkSpeed=d.Move.autoWalkSpeed or 16; local h=getHum(); if h then h.WalkSpeed=State.Move.ws; h.UseJumpPower=true; h.JumpPower=State.Move.jp end end; if d.ESP then State.ESP.tracerMode=d.ESP.tracerMode or "Bottom"; State.ESP.maxDrawDistance=d.ESP.maxDrawDistance or 300; State.ESP.highlightMode=d.ESP.highlightMode or false end; if d.Security and d.Security.shiftLock~=State.Security.shiftLock then toggleShiftLock(d.Security.shiftLock) end; if d.AutoLike then State.AutoLike.radius=d.AutoLike.radius or 100; State.AutoLike.minCD=d.AutoLike.minCD or 2; State.AutoLike.maxCD=d.AutoLike.maxCD or 6 end; if d.HardFling then State.HardFling.power=d.HardFling.power or 5000; State.HardFling.mode=d.HardFling.mode or "Spin" end; if d.SelfSpec then SS.mode=d.SelfSpec.mode or "Manual"; SS.radius=d.SelfSpec.radius or 8; SS.height=d.SelfSpec.height or 3; SS.speed=d.SelfSpec.speed or 1 end; if d.CustomFilter then for k,v in pairs(d.CustomFilter) do State.CustomFilter[k]=v end; applyCustomFilter() end; notify("Config","Loaded: "..s,2,"folder-open") end end end) end})
secFile:Button({Title="Delete Config",Callback=function() if currentConfig~="No config" and currentConfig~="" then pcall(function() if isfile and delfile and isfile("XKID_HUB/"..currentConfig..".json") then delfile("XKID_HUB/"..currentConfig..".json"); pcall(function() configDrop:Refresh(getConfigList(),true) end); currentConfig="No config"; notify("Config","Deleted",2,"trash-2") end end) end end})
secFile:Button({Title="Refresh Files",Callback=function() pcall(function() configDrop:Refresh(getConfigList(),true) end); notify("Config","Files refreshed",1.5,"folder") end})
local secLike = TabSet:Section({Title="Auto Like (Smart)",Icon="heart",Box=true})
secLike:Toggle({Title="Auto Like",Default=false,Callback=function(v) if v then startAutoLike() else stopAutoLike() end end})
secLike:Slider({Title="Like Radius",Desc="0 = all",Step=10,Value={Min=0,Max=500,Default=100},Callback=function(v) State.AutoLike.radius=v end})
secLike:Slider({Title="Min Cooldown",Step=0.5,Value={Min=0.5,Max=10,Default=2},Callback=function(v) State.AutoLike.minCD=v end})
secLike:Slider({Title="Max Cooldown",Step=0.5,Value={Min=1,Max=15,Default=6},Callback=function(v) State.AutoLike.maxCD=v end})
local autoLikeInfo = secLike:Paragraph({Title="Info",Desc="Total likes sent: 0"})
task.spawn(function() while getgenv()._XKID_RUNNING do task.wait(2); pcall(function() autoLikeInfo:SetDesc("Total likes sent: "..State.AutoLike.count) end) end end)

task.delay(0.5,function() pcall(function() for _,t in pairs(Window.Tabs) do for _,s in ipairs(t.Sections) do if s.Expand then s:Expand() end end end end) end)
pcall(function() settings().Rendering.QualityLevel=Enum.QualityLevel.Level02 end)
pcall(function() if setfpscap then setfpscap(9999) end end)

-- ========== FORCE AUTO START ANTI AFK ==========
task.wait(0.5)
pcall(function() if startAFK then startAFK() end; if AntiAFK then AntiAFK.Active=true; AntiAFK.LastActivity=tick(); AntiAFK.CurrentInterval=math.random(20,35) end; if State and State.Security then State.Security.afkActive=true end end)
task.delay(1,function() pcall(function() if startAFK then startAFK() end; if AntiAFK then AntiAFK.Active=true; AntiAFK.LastActivity=tick() end; if State and State.Security then State.Security.afkActive=true end end) end)

task.wait(1.5)
getgenv()._XKID_UI_LOADING=false
notify("System","XKID AKTIF — v"..CURRENT_VERSION,3,"rocket")
task.wait(0.5)
notify("Anti AFK","AUTO ACTIVATED ✓",2,"shield-check")
print("[XKID] Anti AFK force started - ON")