local WindUI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Footagesus/WindUI/main/main.lua"))()
local Window = WindUI:CreateWindow("WindUI Test 🔥")
local Tab = Window:AddTab("Main")
Tab:AddToggle("Test", false, function(state) print(state) end)
Tab:AddButton("Notif", function() WindUI:Notify("Smooth!") end)
