-- XKID V2.1 ULTRA COMPACT
repeat task.wait()until game:IsLoaded()
local W=(function()local s,r=pcall(function()return loadstring(game:HttpGet("https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"))()end)if s then return r else error()end end)()
local E={name="Unknown",wf=false,rf=false,lf=false,isf=false,mf=false,mob=false}
pcall(function()local e=identifyexecutor and identifyexecutor()or getexecutorname and getexecutorname()or"Unknown"E.name=e E.mob=e:find("Hydrogen")or e:find("Arceus")or e:find("Vega")end)
E.wf=type(writefile)=="function"E.rf=type(readfile)=="function"E.lf=type(listfiles)=="function"E.isf=type(isfolder)=="function"E.mf=type(makefolder)=="function"
if not E.wf then getgenv()._XKID_NO_SAVE=true end
local function H(o)local f=http_request or request or(syn and syn.request)or(fluxus and fluxus.request)or(http and http.request)if not f then local hs=game:GetService("HttpService")return{StatusCode=200,Body=hs:GetAsync(o.Url,true),Success=true}end return f(o)end
getgenv()._XKID_REQUEST=H
local function F(t)t=t or 120 pcall(function()if setfpscap then setfpscap(t)end end)pcall(function()local rs=settings():GetService("Rendering")if rs and rs.SetTargetFrameRate then rs:SetTargetFrameRate(t)end end)pcall(function()local ws=game:GetService("Workspace")if ws and ws.SetTargetFrameRate then ws:SetTargetFrameRate(t)end end)end
F(120)
local RS,HS,PL,UI,VI,LT,TP,SS,CG,TCS,SG,RPS=game:GetService("RunService"),game:GetService("HttpService"),game:GetService("Players"),game:GetService("UserInputService"),game:GetService("VirtualUser"),game:GetService("Lighting"),game:GetService("TeleportService"),game:GetService("Stats"),game:GetService("CoreGui"),game:GetService("TextChatService"),game:GetService("StarterGui"),game:GetService("ReplicatedStorage")
local LP=PL.LocalPlayer local CA=workspace.CurrentCamera local MO=not UI.KeyboardEnabled
getgenv()._XKID_UI_LOADING=true
local OL={CT=LT.ClockTime,BR=LT.Brightness,AM=LT.Ambient,OA=LT.OutdoorAmbient,GS=LT.GlobalShadows,EC=LT.ExposureCompensation}
if getgenv()._XKID_RUNNING then getgenv()._XKID_RUNNING=false task.wait(0.5)end
if getgenv()._XKID_ESP_CACHE then for _,c in pairs(getgenv()._XKID_ESP_CACHE)do pcall(function()if c.tx then c.tx:Remove()end if c.tr then c.tr:Remove()end if c.bx then for _,l in ipairs(c.bx)do l:Remove()end end if c.hl then c.hl:Destroy()end end)end end
getgenv()._XKID_ESP_CACHE={}
if getgenv()._XKID_LOADED then pcall(function()for _,v in pairs(CG:GetChildren())do if v.Name=="WindUI"or v.Name=="XKID_FreecamUI"then v:Destroy()end end for _,v in pairs(LT:GetChildren())do if v.Name=="_XKID_FILTER"then v:Destroy()end end if getgenv()._XKID_CONNS then for _,c in pairs(getgenv()._XKID_CONNS)do pcall(function()c:Disconnect()end)end end end)pcall(function()RS:UnbindFromRenderStep("XKIDFreecam")RS:UnbindFromRenderStep("XKIDFly")RS:UnbindFromRenderStep("XKIDSpec")RS:UnbindFromRenderStep("XKIDSelfSpec")RS:UnbindFromRenderStep("XKIDShiftLock")RS:UnbindFromRenderStep("XKIDAutoWalk")end)end
getgenv()._XKID_LOADED=true getgenv()._XKID_RUNNING=true getgenv()._XKID_CONNS={}
local function TC(c)table.insert(getgenv()._XKID_CONNS,c)return c end
local function N(t,c,d,i)pcall(function()W:Notify({Title=t,Content=c,Duration=d or 2,Icon=i or"bell"})end)end
local ST={Move={ws=16,jp=50,ncp=false,infJ=false,flyS=60,aw=false,aws=16},Fly={ac=false,bv=nil,bg=nil,ks={}},HF={ac=false,pw=10000,md="Spin",cp=0,ru=false},Sec={sl=false,sg=nil,al=false},Cin={hu=false,cg={}},Av={ir=false},CF={r=255,g=255,b=255,st=0,ct=0,br=0,ex=0,bl=0,bs=24,ti=14},SS={ac=false,md="Manual",ds=8,he=3,oy=0,op=20,fy=0,fp=0,of=70,rd=8,sp=1},ESP={ac=false,ch=getgenv()._XKID_ESP_CACHE,tm="Bottom",md=300,hl=false,bN=Color3.fromRGB(0,255,150),bS=Color3.fromRGB(220,20,60),bG=Color3.fromRGB(255,165,0),tN=Color3.fromRGB(0,200,255),tS=Color3.fromRGB(220,20,60),tG=Color3.fromRGB(255,165,0),nC=Color3.fromRGB(255,255,255)},AL={ac=false,th=nil,lt=nil,ct=0,rd=100,mn=2,mx=6},UL={cl=false,ctg={},ch={}}}
local CM={Merah=Color3.fromRGB(255,0,0),Hijau=Color3.fromRGB(0,255,0),Biru=Color3.fromRGB(0,0,255),Kuning=Color3.fromRGB(255,255,0),Ungu=Color3.fromRGB(255,0,255),Cyan=Color3.fromRGB(0,255,255),Orange=Color3.fromRGB(255,165,0),Pink=Color3.fromRGB(255,105,180),Putih=Color3.fromRGB(255,255,255),Hitam=Color3.fromRGB(0,0,0),Crimson=Color3.fromRGB(220,20,60)}
local function GR()return LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")end
local function GH()return LP.Character and LP.Character:FindFirstChildOfClass("Humanoid")end
local function GCR(c)if not c then return nil end return c:FindFirstChild("HumanoidRootPart")or c.PrimaryPart or c:FindFirstChild("Head")or c:FindFirstChild("Torso")or c:FindFirstChild("UpperTorso")or c:FindFirstChildWhichIsA("BasePart")end
local function GDN()local t={}for _,p in pairs(PL:GetPlayers())do if p~=LP then table.insert(t,p.DisplayName)end end if #t==0 then table.insert(t,"N/A")end return t end
local function GDNS()local t={"[Self]"}for _,p in pairs(PL:GetPlayers())do if p~=LP then table.insert(t,p.DisplayName)end end if #t==1 then table.insert(t,"N/A")end return t end
local function FPD(s)if s=="[Self]"then return LP end for _,p in pairs(PL:GetPlayers())do if p.DisplayName==s or p.Name==s then return p end end return nil end
local function FT(s)local m=math.floor(s/60)local s2=s%60 return string.format("%02d:%02d",m,s2)end
local function MB(v,mx,l)local f=math.clamp(math.floor((v/mx)*l),0,l)return string.rep("█",f)..string.rep("░",l-f)end
local function IOG()local r=GR()if not r then return false end local p=RaycastParams.new()p.FilterType=Enum.RaycastFilterType.Exclude p.FilterDescendantsInstances={LP.Character}return workspace:Raycast(r.Position,Vector3.new(0,-5,0),p)~=nil end
local function GCL()local l={}if E.isf and E.lf then pcall(function()if isfolder and isfolder("XKID_HUB")then for _,f in ipairs(listfiles("XKID_HUB"))do if f:match("%.json$")then local n=f:match("([^/\\]+)%.json$")if n then table.insert(l,n)end end end end end)end if #l==0 then table.insert(l,"No config")end return l end
local STT=os.time()local CMN=nil local LMC=0 local SFPS=60 local SP=0
TC(RS.RenderStepped:Connect(function(dt)if dt>0 then SFPS=math.floor(1/dt)end end))
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(0.5)pcall(function()local it=SS.Network.ServerStatsItem["Data Ping"]if it then SP=math.floor(it:GetValue())end end)end end)
task.spawn(function()while getgenv()._XKID_RUNNING do pcall(function()if tick()-LMC>30 or not CMN then CMN=game:GetService("MarketplaceService"):GetProductInfo(game.PlaceId).Name LMC=tick()end end)task.wait(5)end end)
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(120)collectgarbage("collect")end end)
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(30)F(120)end end)
TC(LP.CharacterAdded:Connect(function()task.wait(0.5)F(120)end))
local VIM=pcall(function()return game:GetService("VirtualInputManager")end)and game:GetService("VirtualInputManager")or nil
local AFK={ac=false,th=nil,la=0,lj=0}local JI=420 local CI=10
local function IUA()if UI:IsKeyDown(Enum.KeyCode.W)or UI:IsKeyDown(Enum.KeyCode.A)or UI:IsKeyDown(Enum.KeyCode.S)or UI:IsKeyDown(Enum.KeyCode.D)or UI:IsKeyDown(Enum.KeyCode.Space)or UI:IsKeyDown(Enum.KeyCode.LeftShift)or UI:IsKeyDown(Enum.KeyCode.MouseButton1)then return true end if MO then if #UI:GetTouchPositions()>0 then return true end end local hrp,gh=GR(),GH()if hrp and gh and gh.MoveDirection.Magnitude>0.1 then return true end return false end
local function SSA()if VI and VI.ClickButton2 then pcall(function()local vp=CA.ViewportSize VI:ClickButton2(Vector2.new(vp.X-5,vp.Y-5))end)return true end pcall(function()local r=RPS:FindFirstChild("Remotes")if r then local sr=r:FindFirstChild("Ping")or r:FindFirstChild("Heartbeat")if sr and sr.FireServer then sr:FireServer()return true end end end)local gh=GH()if gh then pcall(function()gh:ChangeState(Enum.HumanoidStateType.Jumping)end)return true end pcall(function()local cf=CA.CFrame CA.CFrame=cf*CFrame.Angles(0,math.rad(0.5),0)task.wait(0.05)CA.CFrame=cf end)return true end
local function SAFK()if AFK.ac then return end AFK.ac=true ST.Sec.afkActive=true AFK.la=tick()AFK.lj=tick()AFK.th=task.spawn(function()while AFK.ac do task.wait(CI)local n=tick()if IUA()then AFK.la=n elseif n-AFK.la>=JI and n-AFK.lj>=JI then SSA()AFK.lj=n end end end)N("Anti AFK","ON (7min Jump)",1.5,"shield-check")end
local function STAFK()AFK.ac=false ST.Sec.afkActive=false if AFK.th then task.cancel(AFK.th)AFK.th=nil end N("Anti AFK","OFF",1.5,"shield-check")end
function ToggleAntiAFK()if AFK.ac then STAFK()else SAFK()end end
TC(LP.CharacterAdded:Connect(function(c)task.wait(0.5)local h=c:FindFirstChildOfClass("Humanoid")if h then if ST.Move.ws~=16 then h.WalkSpeed=ST.Move.ws end if ST.Move.jp~=50 then h.UseJumpPower=true h.JumpPower=ST.Move.jp end end if ST.Sec.sl then task.wait(0.2)local r=GR()if r then if ST.Sec.sg then ST.Sec.sg:Destroy()end ST.Sec.sg=Instance.new("BodyGyro",r)ST.Sec.sg.MaxTorque=Vector3.new(9e9,9e9,9e9)ST.Sec.sg.P=50000 ST.Sec.sg.D=1000 end end end))
local function TSL(v)ST.Sec.sl=v if v then local r=GR()if r then if ST.Sec.sg then ST.Sec.sg:Destroy()end ST.Sec.sg=Instance.new("BodyGyro",r)ST.Sec.sg.MaxTorque=Vector3.new(9e9,9e9,9e9)ST.Sec.sg.P=50000 ST.Sec.sg.D=1000 end RS:BindToRenderStep("XKIDShiftLock",Enum.RenderPriority.Camera.Value+2,function()if not ST.Sec.sl then return end local r2,gy=GR(),ST.Sec.sg if r2 and gy and gy.Parent==r2 then local fl=Vector3.new(CA.CFrame.LookVector.X,0,CA.CFrame.LookVector.Z)if fl.Magnitude>0.01 then gy.CFrame=CFrame.new(r2.Position,r2.Position+fl)end end end)N("Shift Lock","ON",1.5,"lock")else RS:UnbindFromRenderStep("XKIDShiftLock")if ST.Sec.sg then ST.Sec.sg:Destroy()ST.Sec.sg=nil end N("Shift Lock","OFF",1.5,"unlock")end end
local rCF,rWS,rJP,rZ=nil,16,50,400
local function RC()if ST.Av.ir then return end local c,r=LP.Character,GR()if not c or not r then N("Error","Character not found",2,"circle-alert")return end ST.Av.ir=true rCF=r.CFrame rWS=ST.Move.ws rJP=ST.Move.jp rZ=LP.CameraMaxZoomDistance N("Refresh","Reloading...",1.5,"refresh-cw")pcall(function()c:BreakJoints()end)local w=0 repeat task.wait(0.1)w=w+0.1 until not LP.Character or w>2 if LP.Character then pcall(function()LP.Character:Destroy()end)task.wait(0.3)end if not LP.Character then pcall(function()LP:LoadCharacter()end)end task.delay(12,function()if ST.Av.ir then ST.Av.ir=false rCF=nil N("Error","Refresh timeout",3,"circle-alert")end end)end
TC(LP.CharacterAdded:Connect(function(nc)if not ST.Av.ir or not rCF then return end task.wait(0.3)local nr=nc:FindFirstChild("HumanoidRootPart")or nc:WaitForChild("HumanoidRootPart",8)local nh=nc:FindFirstChildOfClass("Humanoid")or nc:WaitForChild("Humanoid",8)if nr and nh then repeat task.wait()until nh.Health>0 and nr:IsDescendantOf(workspace)nr.CFrame=rCF+Vector3.new(0,4,0)nr.AssemblyLinearVelocity=Vector3.zero nr.AssemblyAngularVelocity=Vector3.zero nh.WalkSpeed=rWS nh.UseJumpPower=true nh.JumpPower=rJP CA.CameraSubject=nh CA.CameraType=Enum.CameraType.Custom pcall(function()LP.CameraMaxZoomDistance=rZ end)N("Refresh","Done",2,"check-circle")end ST.Av.ir=false rCF=nil end))
local TPt={cc=nil,ca=false,ta=false,tl=nil}
local function ETP()local r=GR()if not r then return end local m=LP:GetMouse()if m.Hit then r.CFrame=CFrame.new(m.Hit.Position+Vector3.new(0,3.5,0))r.AssemblyLinearVelocity=Vector3.zero end end
local function TSTP(v)TPt.ca=v if v then pcall(function()local t=Instance.new("Tool")t.Name="TP Tool"t.RequiresHandle=false t.Parent=LP.Backpack TPt.tl=t TPt.ta=false t.Activated:Connect(function()TPt.ta=not TPt.ta end)end)TPt.cc=TC(UI.InputBegan:Connect(function(inp,gp)if gp then return end if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then if TPt.ta then ETP()TPt.ta=false end end end))N("Smart TP","ON",2,"map-pin")else if TPt.cc then TPt.cc:Disconnect()TPt.cc=nil end pcall(function()if TPt.tl then TPt.tl:Destroy()TPt.tl=nil end end)TPt.ta=false N("Smart TP","OFF",1.5,"map-pin")end end
local function SAW()RS:UnbindFromRenderStep("XKIDAutoWalk")ST.Move.aw=true local h=GH()if h then h.WalkSpeed=ST.Move.aws end RS:BindToRenderStep("XKIDAutoWalk",Enum.RenderPriority.Character.Value+1,function()if not ST.Move.aw then return end local r,h=GR(),GH()if not r or not h then return end if h.MoveDirection.Magnitude>0.1 then return end local cd=CA.CFrame.LookVector local md=Vector3.new(cd.X,0,cd.Z).Unit r.CFrame=r.CFrame+md*(ST.Move.aws/60)end)N("Auto Walk","ON",1.5,"play")end
local function STAW()RS:UnbindFromRenderStep("XKIDAutoWalk")ST.Move.aw=false local h=GH()if h then h.WalkSpeed=ST.Move.ws end N("Auto Walk","OFF",1.5,"play")end
local fmt,fts,fj,fcs,fv=nil,nil,Vector2.zero,{},Vector3.zero
local function SFC()local ks={}table.insert(fcs,UI.InputBegan:Connect(function(inp,gp)if gp then return end local k=inp.KeyCode if k==Enum.KeyCode.W or k==Enum.KeyCode.A or k==Enum.KeyCode.S or k==Enum.KeyCode.D or k==Enum.KeyCode.E or k==Enum.KeyCode.Q then ks[k]=true end end))table.insert(fcs,UI.InputEnded:Connect(function(inp)ks[inp.KeyCode]=nil end))table.insert(fcs,UI.InputBegan:Connect(function(inp,gp)if gp or inp.UserInputType~=Enum.UserInputType.Touch then return end if inp.Position.X<=CA.ViewportSize.X/2 then if not fmt then fmt=inp fts=inp.Position end end end))table.insert(fcs,UI.TouchMoved:Connect(function(inp)if inp==fmt and fts then local dx=inp.Position.X-fts.X local dy=inp.Position.Y-fts.Y local function ad(v,d,m)if math.abs(v)<d then return 0 end return math.clamp((v-math.sign(v)*d)/(m-d),-1,1)end fj=Vector2.new(ad(dx,25,80),ad(dy,20,80))end end))table.insert(fcs,UI.InputEnded:Connect(function(inp)if inp.UserInputType~=Enum.UserInputType.Touch then return end if inp==fmt then fmt=nil fts=nil fj=Vector2.zero end end))ST.Fly.ks=ks end
local function STFC()for _,c in ipairs(fcs)do c:Disconnect()end fcs={}fmt=nil fts=nil fj=Vector2.zero ST.Fly.ks={}end
local function TF(v)if not v then ST.Fly.ac=false STFC()RS:UnbindFromRenderStep("XKIDFly")pcall(function()if ST.Fly.bv then ST.Fly.bv:Destroy()end end)pcall(function()if ST.Fly.bg then ST.Fly.bg:Destroy()end end)ST.Fly.bv=nil ST.Fly.bg=nil fv=Vector3.zero local h=GH()if h then h.PlatformStand=false h:ChangeState(Enum.HumanoidStateType.GettingUp)h.WalkSpeed=ST.Move.ws h.UseJumpPower=true h.JumpPower=ST.Move.jp end N("Fly","OFF",1.5,"bird")return end local r,h=GR(),GH()if not r or not h then return end ST.Fly.ac=true h.PlatformStand=true fv=Vector3.zero ST.Fly.bv=Instance.new("BodyVelocity",r)ST.Fly.bv.MaxForce=Vector3.new(9e9,9e9,9e9)ST.Fly.bg=Instance.new("BodyGyro",r)ST.Fly.bg.MaxTorque=Vector3.new(9e9,9e9,9e9)ST.Fly.bg.P=50000 SFC()N("Fly","ON",2,"bird")RS:BindToRenderStep("XKIDFly",Enum.RenderPriority.Camera.Value+1,function()if not ST.Fly.ac then return end local r2=GR()if not r2 then return end local cf=CA.CFrame local spd=ST.Move.flyS local mv=Vector3.zero local ks=ST.Fly.ks or{} if MO then mv=cf.LookVector*(-fj.Y)+cf.RightVector*fj.X else if ks[Enum.KeyCode.W]then mv=mv+cf.LookVector end if ks[Enum.KeyCode.S]then mv=mv-cf.LookVector end if ks[Enum.KeyCode.D]then mv=mv+cf.RightVector end if ks[Enum.KeyCode.A]then mv=mv-cf.RightVector end if ks[Enum.KeyCode.E]then mv=mv+Vector3.new(0,1,0)end if ks[Enum.KeyCode.Q]then mv=mv-Vector3.new(0,1,0)end end if mv.Magnitude>0 then fv=fv:Lerp(mv.Unit*spd,0.15)else fv=fv:Lerp(IOG()and Vector3.zero or Vector3.new(0,-0.8,0),0.08)end if ST.Fly.bv and ST.Fly.bv.Parent then ST.Fly.bv.Velocity=fv end if ST.Fly.bg and ST.Fly.bg.Parent then ST.Fly.bg.CFrame=CFrame.new(r2.Position,r2.Position+cf.LookVector)end end)end
local FC={ac=false,pos=Vector3.zero,pi=0,ya=0,ro=0,sp=3,se=0.25,of=70,sWS=16,sJP=16,wa=false}local cV,yV,pV,rV,hV=Vector3.zero,0,0,0,0 local fmT,fmS,fmJ,frT,frL,fKH,fCs=nil,nil,Vector2.zero,nil,nil,{},{}
local FC_UB={up=false,dn=false,rl=false,rr=false,zi=false,zo=false}local FC_UH=false local fB={}
local FCUI=Instance.new("ScreenGui")FCUI.Name="XKID_FreecamUI"FCUI.ResetOnSpawn=false FCUI.ZIndexBehavior=Enum.ZIndexBehavior.Global FCUI.Enabled=false FCUI.Parent=CG getgenv()._XKID_FCUI=FCUI
local function MFB(n,t,p,a)local b=Instance.new("TextButton",FCUI)b.Name=n b.Size=UDim2.new(0,44,0,44)b.Position=p b.BackgroundColor3=Color3.fromRGB(15,15,15)b.BackgroundTransparency=0.4 b.Text=t b.TextColor3=Color3.fromRGB(255,255,255)b.TextSize=18 b.Font=Enum.Font.GothamBold b.AutoButtonColor=false Instance.new("UICorner",b).CornerRadius=UDim.new(0,10)local us=Instance.new("UIStroke",b)us.Color=Color3.fromRGB(220,20,60)us.Thickness=2 us.Transparency=0.3 local ind=Instance.new("Frame",b)ind.Name="Indicator"ind.Size=UDim2.new(0,6,0,6)ind.Position=UDim2.new(0,4,0,4)ind.BackgroundColor3=Color3.fromRGB(60,60,60)Instance.new("UICorner",ind).CornerRadius=UDim.new(1,0)local function pr(d)FC_UB[a]=d b.BackgroundTransparency=d and 0.05 or 0.4 ind.BackgroundColor3=d and Color3.fromRGB(255,60,60)or Color3.fromRGB(60,60,60)end b.InputBegan:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then pr(true)end end)b.InputEnded:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.Touch or inp.UserInputType==Enum.UserInputType.MouseButton1 then pr(false)end end)b.MouseLeave:Connect(function()pr(false)end)table.insert(fB,b)return b end
MFB("BtnRollL","L",UDim2.new(1,-156,0.5,-66),"rl")MFB("BtnRollR","R",UDim2.new(1,-58,0.5,-66),"rr")MFB("BtnUp","↑",UDim2.new(1,-107,0.5,-110),"up")MFB("BtnDown","↓",UDim2.new(1,-107,0.5,-22),"dn")MFB("BtnZIn","+",UDim2.new(1,-156,0.5,-22),"zi")MFB("BtnZOut","-",UDim2.new(1,-58,0.5,-22),"zo")
local eBtn=Instance.new("TextButton",FCUI)eBtn.Name="BtnEye"eBtn.Size=UDim2.new(0,44,0,44)eBtn.Position=UDim2.new(1,-107,0.5,-66)eBtn.BackgroundColor3=Color3.fromRGB(15,15,15)eBtn.BackgroundTransparency=0.6 eBtn.Text="👁"eBtn.TextColor3=Color3.fromRGB(255,255,255)eBtn.TextSize=18 eBtn.Font=Enum.Font.GothamBold eBtn.AutoButtonColor=false Instance.new("UICorner",eBtn).CornerRadius=UDim.new(0,10)Instance.new("UIStroke",eBtn)
local function TFE()FC_UH=not FC_UH eBtn.Text=FC_UH and"👁‍🗨"or"👁"for _,b in ipairs(fB)do b.Visible=not FC_UH end end
eBtn.MouseButton1Click:Connect(TFE)eBtn.InputBegan:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.Touch then TFE()end end)
local function SFCC()fKH={}table.insert(fCs,UI.InputBegan:Connect(function(inp,gp)if gp then return end fKH[inp.KeyCode]=true if inp.UserInputType==Enum.UserInputType.MouseButton2 then FC._mr=true UI.MouseBehavior=Enum.MouseBehavior.LockCurrentPosition end end))table.insert(fCs,UI.InputEnded:Connect(function(inp)fKH[inp.KeyCode]=false if inp.UserInputType==Enum.UserInputType.MouseButton2 then FC._mr=false UI.MouseBehavior=Enum.MouseBehavior.Default end end))table.insert(fCs,UI.InputChanged:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.MouseMovement and FC._mr then yV=yV-inp.Delta.X*FC.se*120 pV=pV-inp.Delta.Y*FC.se*120 end end))table.insert(fCs,UI.InputBegan:Connect(function(inp,gp)if gp or inp.UserInputType~=Enum.UserInputType.Touch then return end if inp.Position.X>CA.ViewportSize.X/2 then if not frT then frT=inp frL=inp.Position end else if not fmT then fmT=inp fmS=inp.Position fmJ=Vector2.zero end end end))table.insert(fCs,UI.TouchMoved:Connect(function(inp)if inp==frT and frL then local dx=inp.Position.X-frL.X local dy=inp.Position.Y-frL.Y frL=inp.Position yV=yV-dx*FC.se*80 pV=pV-dy*FC.se*80 end if inp==fmT and fmS then local dx=inp.Position.X-fmS.X local dy=inp.Position.Y-fmS.Y local function ad(v,d,m)if math.abs(v)<d then return 0 end return math.clamp((v-math.sign(v)*d)/(m-d),-1,1)end fmJ=Vector2.new(ad(dx,15,70),ad(dy,15,70))end end))table.insert(fCs,UI.InputEnded:Connect(function(inp)if inp.UserInputType~=Enum.UserInputType.Touch then return end if inp==frT then frT=nil frL=nil end if inp==fmT then fmT=nil fmS=nil fmJ=Vector2.zero end end))end
local function STFCC()for _,c in ipairs(fCs)do c:Disconnect()end fCs={}fKH={}FC._mr=false UI.MouseBehavior=Enum.MouseBehavior.Default end
local function SFCL()RS:BindToRenderStep("XKIDFreecam",Enum.RenderPriority.Camera.Value+1,function(dt)if not FC.ac then return end CA.CameraType=Enum.CameraType.Scriptable local sdt=math.clamp(dt,0.001,0.05)yV=yV*math.max(0,1-sdt*14)pV=pV*math.max(0,1-sdt*14)FC.ya=FC.ya+yV*sdt FC.pi=math.clamp(FC.pi+pV*sdt,-80,80)local rt=0 if FC_UB.rl then rt=-100 elseif FC_UB.rr then rt=100 end rV=rV+(rt-rV)*math.clamp(sdt*5,0,1)FC.ro=math.clamp(FC.ro+rV*sdt,-100,100)local cf=CFrame.new(FC.pos)*CFrame.Angles(0,math.rad(FC.ya),0)*CFrame.Angles(math.rad(FC.pi),0,0)local jx,jy=fmJ.X,fmJ.Y if not MO then if fKH[Enum.KeyCode.W]then jy=jy-1 end if fKH[Enum.KeyCode.S]then jy=jy+1 end if fKH[Enum.KeyCode.D]then jx=jx+1 end if fKH[Enum.KeyCode.A]then jx=jx-1 end end local rm=Vector2.new(jx,jy)if rm.Magnitude>1 then rm=rm.Unit end cV=cV:Lerp((cf.LookVector*(-rm.Y)+cf.RightVector*rm.X)*(FC.sp*60),math.clamp(sdt*3.5,0,1))local ht=0 if fKH[Enum.KeyCode.E]or FC_UB.up then ht=FC.sp*60 end if fKH[Enum.KeyCode.Q]or FC_UB.dn then ht=-FC.sp*60 end if ht==0 then hV=hV*math.max(0,1-sdt*10)else hV=hV+(ht-hV)*math.clamp(sdt*3,0,1)end if FC_UB.zi then CA.FieldOfView=math.clamp(CA.FieldOfView-1.2,10,120)end if FC_UB.zo then CA.FieldOfView=math.clamp(CA.FieldOfView+1.2,10,120)end FC.pos=FC.pos+(cV+Vector3.new(0,hV,0))*sdt CA.CFrame=CFrame.new(FC.pos)*CFrame.Angles(0,math.rad(FC.ya),0)*CFrame.Angles(math.rad(FC.pi),0,0)*CFrame.Angles(0,0,math.rad(FC.ro))end)end
local function STFCL()RS:UnbindFromRenderStep("XKIDFreecam")end
local function FCFC()STFCL()STFCC()local h,r=GH(),GR()if h then h.WalkSpeed=FC.sWS h.UseJumpPower=true h.JumpPower=FC.sJP end if FC.wa and r then r.Anchored=false FC.wa=false end CA.CameraType=Enum.CameraType.Custom CA.FieldOfView=FC.of if getgenv()._XKID_FCUI then getgenv()._XKID_FCUI.Enabled=false end for k in pairs(FC_UB)do FC_UB[k]=false end FC_UH=false eBtn.Text="👁"for _,b in ipairs(fB)do b.Visible=true end end
local SSs=ST.SS
local stm,spin,spinD,span,scns=nil,{},nil,Vector2.zero,{}
local function SSSG()scns={}table.insert(scns,UI.InputBegan:Connect(function(inp,gp)if gp or not SSs.ac or inp.UserInputType~=Enum.UserInputType.Touch then return end table.insert(spin,inp)stm=#spin==1 and inp or nil end))table.insert(scns,UI.InputChanged:Connect(function(inp)if not SSs.ac or inp.UserInputType~=Enum.UserInputType.Touch then return end if #spin==1 and inp==stm then span=span+Vector2.new(inp.Delta.X,inp.Delta.Y)elseif #spin>=2 then local d=(spin[1].Position-spin[2].Position).Magnitude if spinD then local diff=d-spinD CA.FieldOfView=math.clamp(CA.FieldOfView-diff*0.15,10,120)SSs.rd=math.clamp(SSs.rd-diff*0.03,3,30)end spinD=d end end))table.insert(scns,UI.InputEnded:Connect(function(inp)if inp.UserInputType~=Enum.UserInputType.Touch then return end for i,v in ipairs(spin)do if v==inp then table.remove(spin,i)break end end spinD=nil stm=#spin==1 and spin[1] or nil end))end
local function STSSG()for _,c in ipairs(scns)do c:Disconnect()end scns={}stm=nil spin={}spinD=nil span=Vector2.zero end
local function SSSL()RS:UnbindFromRenderStep("XKIDSelfSpec")RS:BindToRenderStep("XKIDSelfSpec",Enum.RenderPriority.Camera.Value+1,function()if not SSs.ac then return end pcall(function()local tc=LP.Character local tr=GCR(tc)if not tr then return end CA.CameraType=Enum.CameraType.Scriptable local pn,sn=span,MO and 0.2 or 0.3 span=Vector2.zero if SSs.md=="First Person"then local hd=tc:FindFirstChild("Head")local og=hd and hd.Position or tr.Position+Vector3.new(0,1.5,0)SSs.fy=SSs.fy-pn.X*sn SSs.fp=math.clamp(SSs.fp-pn.Y*sn,-85,85)CA.CFrame=CFrame.new(og)*CFrame.Angles(0,math.rad(SSs.fy),0)*CFrame.Angles(math.rad(SSs.fp),0,0)else if #spin==0 and pn.Magnitude<0.01 then local dt=0.016 if SSs.md=="Slow Orbit"then SSs.oy=SSs.oy+dt*25*SSs.sp elseif SSs.md=="Vertical Swing"then SSs.op=20+math.sin(tick()*SSs.sp*1.5)*40 SSs.oy=SSs.oy+dt*10*SSs.sp elseif SSs.md=="Figure 8"then SSs.oy=math.sin(tick()*SSs.sp*0.8)*80 SSs.op=20+math.sin(tick()*SSs.sp*1.2)*35 elseif SSs.md=="Cinematic Drift"then SSs.oy=SSs.oy+dt*15*SSs.sp SSs.op=20+math.sin(tick()*SSs.sp*0.7)*15 elseif SSs.md=="Top Down"then SSs.op=-75 SSs.oy=SSs.oy+dt*8*SSs.sp end end SSs.oy=SSs.oy+pn.X*sn SSs.op=math.clamp(SSs.op+pn.Y*sn,-75,75)local h=(SSs.md=="Top Down")and 15 or(SSs.he or 3)CA.CFrame=CFrame.new((CFrame.new(tr.Position+Vector3.new(0,h,0))*CFrame.Angles(0,math.rad(-SSs.oy),0)*CFrame.Angles(math.rad(-SSs.op),0,0)*CFrame.new(0,0,SSs.rd)).Position,tr.Position+Vector3.new(0,h,0))end end)end)end
local function STSSL()RS:UnbindFromRenderStep("XKIDSelfSpec")CA.CameraType=Enum.CameraType.Custom CA.FieldOfView=SSs.of SSs.ac=false SSs.oy=0 SSs.op=20 SSs.fy=0 SSs.fp=0 SSs.rd=8 SSs.he=3 span=Vector2.zero end
local function TSS(v)if v then if FC.ac then FCFC()end if ST.Fly.ac then STFC()end if Sp and Sp.ac then STSPC()end if TPt.cc then TPt.cc:Disconnect()TPt.cc=nil end SSs.ac=true SSs.of=CA.FieldOfView SSs.oy=0 SSs.op=20 SSs.fy=0 SSs.fp=0 SSs.rd=SSs.rd or 8 SSs.he=SSs.he or 3 SSSG()SSSL()N("Self-Spectate","ON — "..(SSs.md or"Manual"),2,"camera")else SSs.ac=false STSSG()STSSL()N("Self-Spectate","OFF",1.5,"camera")end end
local Sp={ac=false,tg=nil,md="third",ds=8,of=70,oy=0,op=0,fy=0,fp=0,is=false}local stm2,spin2,spinD2,span2,scns2=nil,{},nil,Vector2.zero,{}
local function SSPC()table.insert(scns2,UI.InputBegan:Connect(function(inp,gp)if gp or not Sp.ac or inp.UserInputType~=Enum.UserInputType.Touch then return end table.insert(spin2,inp)stm2=#spin2==1 and inp or nil end))table.insert(scns2,UI.InputChanged:Connect(function(inp)if not Sp.ac or inp.UserInputType~=Enum.UserInputType.Touch then return end if #spin2==1 and inp==stm2 then span2=span2+Vector2.new(inp.Delta.X,inp.Delta.Y)elseif #spin2>=2 then local d=(spin2[1].Position-spin2[2].Position).Magnitude if spinD2 then local diff=d-spinD2 CA.FieldOfView=math.clamp(CA.FieldOfView-diff*0.15,10,120)if Sp.md=="third"then Sp.ds=math.clamp(Sp.ds-diff*0.03,3,30)end end spinD2=d end end))table.insert(scns2,UI.InputEnded:Connect(function(inp)if inp.UserInputType~=Enum.UserInputType.Touch then return end for i,v in ipairs(spin2)do if v==inp then table.remove(spin2,i)break end end spinD2=nil stm2=#spin2==1 and spin2[1] or nil end))end
local function STSPC()for _,c in ipairs(scns2)do c:Disconnect()end scns2={}stm2=nil spin2={}spinD2=nil span2=Vector2.zero end
local function SSPL()RS:BindToRenderStep("XKIDSpec",Enum.RenderPriority.Camera.Value+1,function()if not Sp.ac then return end pcall(function()local tc,tr if Sp.is then tc=LP.Character tr=GCR(tc)else if not Sp.tg or not Sp.tg.Character then Sp.ac=false STSPL()STSPC()CA.CameraType=Enum.CameraType.Custom CA.FieldOfView=Sp.of return end tc=Sp.tg.Character tr=tc:FindFirstChild("HumanoidRootPart")end if not tr then if not Sp.is then Sp.ac=false STSPL()STSPC()CA.CameraType=Enum.CameraType.Custom CA.FieldOfView=Sp.of end return end CA.CameraType=Enum.CameraType.Scriptable local pn,sn=span2,0.3 span2=Vector2.zero if Sp.md=="third"then Sp.oy=Sp.oy+pn.X*sn Sp.op=math.clamp(Sp.op+pn.Y*sn,-75,75)CA.CFrame=CFrame.new((CFrame.new(tr.Position)*CFrame.Angles(0,math.rad(-Sp.oy),0)*CFrame.Angles(math.rad(-Sp.op),0,0)*CFrame.new(0,0,Sp.ds)).Position,tr.Position+Vector3.new(0,1,0))else local hd=tc:FindFirstChild("Head")local og=hd and hd.Position or tr.Position+Vector3.new(0,1.5,0)Sp.fy=Sp.fy-pn.X*sn Sp.fp=math.clamp(Sp.fp-pn.Y*sn,-85,85)CA.CFrame=CFrame.new(og)*CFrame.Angles(0,math.rad(Sp.fy),0)*CFrame.Angles(math.rad(Sp.fp),0,0)end end)end)end
local function STSPL()RS:UnbindFromRenderStep("XKIDSpec")end
local hfC,hfRC,hfBAV=nil,nil,nil
local function SHF()if ST.HF.ac then return end ST.HF.ac=true ST.Move.ncp=true ST.HF.cp=0 ST.HF.ru=true local r=GR()if r then hfBAV=Instance.new("BodyAngularVelocity",r)hfBAV.MaxTorque=Vector3.new(9e9,9e9,9e9)hfBAV.P=100000 end local rs=tick()hfRC=TC(RS.Heartbeat:Connect(function()if not ST.HF.ru then return end local t=math.clamp((tick()-rs)/2,0,1)ST.HF.cp=ST.HF.pw*t if t>=1 then ST.HF.cp=ST.HF.pw ST.HF.ru=false end end))hfC=TC(RS.Heartbeat:Connect(function()if not ST.HF.ac then return end local r2=GR()if not r2 then return end if ST.HF.md=="Spin"then if hfBAV and hfBAV.Parent then hfBAV.AngularVelocity=Vector3.new(0,ST.HF.cp,0)end elseif ST.HF.md=="Shake"then if hfBAV and hfBAV.Parent then local sx=(math.random()-0.5)*ST.HF.cp*0.5 local sy=(math.random()-0.5)*ST.HF.cp*0.3 local sz=(math.random()-0.5)*ST.HF.cp*0.5 hfBAV.AngularVelocity=Vector3.new(sx,sy,sz)end end if LP.Character then for _,p in pairs(LP.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end end))N("Hard Fling","ON — "..ST.HF.md,2,"zap")end
local function STHF()ST.HF.ac=false ST.HF.ru=false ST.HF.cp=0 if hfC then hfC:Disconnect()hfC=nil end if hfRC then hfRC:Disconnect()hfRC=nil end if hfBAV then hfBAV:Destroy()hfBAV=nil end local r=GR()if r then pcall(function()r.AssemblyAngularVelocity=Vector3.zero r.AssemblyLinearVelocity=Vector3.zero end)end if LP.Character then for _,p in pairs(LP.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=true end end end N("Hard Fling","OFF",1.5,"zap")end
local function RFL()for _,v in pairs(LT:GetChildren())do if v.Name=="_XKID_FILTER"then v:Destroy()end end end
local function ACF()RFL()LT.Brightness=OL.BR LT.Ambient=OL.AM LT.OutdoorAmbient=OL.OA LT.GlobalShadows=OL.GS LT.ExposureCompensation=ST.CF.ex local cc=Instance.new("ColorCorrectionEffect",LT)cc.Name="_XKID_FILTER"cc.TintColor=Color3.fromRGB(ST.CF.r,ST.CF.g,ST.CF.b)cc.Saturation=ST.CF.st cc.Contrast=ST.CF.ct cc.Brightness=ST.CF.br local bl=Instance.new("BloomEffect",LT)bl.Name="_XKID_FILTER"bl.Intensity=ST.CF.bl bl.Size=ST.CF.bs LT.ClockTime=ST.CF.ti end
local FP={Default={r=255,g=255,b=255,st=0,ct=0,br=0,ex=0,bl=0,bs=24,ti=14},Mendung={r=180,g=185,b=200,st=-0.3,ct=0.1,br=-0.15,ex=0,bl=0.05,bs=24,ti=10},CoolBlue={r=180,g=200,b=255,st=0.1,ct=0.15,br=0.05,ex=0,bl=0.2,bs=24,ti=12},SoftFade={r=255,g=240,b=235,st=-0.1,ct=-0.05,br=0.1,ex=0,bl=0.4,bs=35,ti=15},FullBright={r=255,g=255,b=255,st=0,ct=0,br=0,ex=0,bl=0,bs=24,ti=12},Night={r=200,g=200,b=255,st=0.1,ct=0.2,br=0,ex=0,bl=0.15,bs=24,ti=1},Senja={r=255,g=180,b=120,st=0.2,ct=0.1,br=0.05,ex=0,bl=0.5,bs=40,ti=17.5},Golden={r=255,g=200,b=100,st=0.1,ct=0.15,br=0.1,ex=0,bl=0.4,bs=35,ti=17.5}}
local function AF(n)RFL()LT.ClockTime=OL.CT LT.Brightness=OL.BR LT.Ambient=OL.AM LT.OutdoorAmbient=OL.OA LT.GlobalShadows=OL.GS LT.ExposureCompensation=OL.EC if n=="Default"then ST.CF={r=255,g=255,b=255,st=0,ct=0,br=0,ex=0,bl=0,bs=24,ti=14}N("Visuals","Default",1.5,"palette")return end if n=="Custom"then ACF()N("Visuals","Custom FX",1.5,"palette")return end local p=FP[n]if p then LT.ClockTime=p.ti or 14 LT.Brightness=p.lb or 1 LT.ExposureCompensation=p.ex or 0 LT.GlobalShadows=p.sh~=false local cc=Instance.new("ColorCorrectionEffect",LT)cc.Name="_XKID_FILTER"cc.TintColor=Color3.fromRGB(p.r,p.g,p.b)cc.Saturation=p.st or 0 cc.Contrast=p.ct or 0 cc.Brightness=p.br or 0 local bl=Instance.new("BloomEffect",LT)bl.Name="_XKID_FILTER"bl.Intensity=p.bl or 0 bl.Size=p.bs or 24 for k,v in pairs(p)do if ST.CF[k]~=nil then ST.CF[k]=v end end N("Visuals",n,2,"palette")else N("Visuals","Filter not found",2,"circle-alert")end end
local eL={}
local function IEP(p)if ST.ESP.ch[p]then return end local c={tx=nil,tr=nil,bx={},hl=nil,is=false,ig=false,rs=""}pcall(function()c.tx=Drawing.new("Text")if c.tx then c.tx.Center=true c.tx.Outline=true c.tx.Font=2 c.tx.Size=13 c.tx.ZIndex=2 end c.tr=Drawing.new("Line")if c.tr then c.tr.Thickness=1.5 c.tr.ZIndex=1 end for i=1,4 do local l=Drawing.new("Line")if l then l.Thickness=1.5 l.ZIndex=1 c.bx[i]=l end end end)ST.ESP.ch[p]=c end
local function CEP(p)local c=ST.ESP.ch[p]if not c then return end pcall(function()if c.tx then c.tx:Remove()end end)pcall(function()if c.tr then c.tr:Remove()end end)for _,l in ipairs(c.bx)do pcall(function()if l then l:Remove()end end)end pcall(function()if c.hl then c.hl:Destroy()end end)ST.ESP.ch[p]=nil end
TC(PL.PlayerRemoving:Connect(CEP))
task.spawn(function()while getgenv()._XKID_RUNNING do if ST.ESP.ac then local tmp={}local mh=GCR(LP.Character)for _,p in pairs(PL:GetPlayers())do if p~=LP and p.Character then local is,ig,rs=false,false,""for _,v in pairs(p.Character:GetChildren())do if v:IsA("BasePart")and(v.Size.X>30 or v.Size.Y>30 or v.Size.Z>30)then is=true rs="Blocker"break elseif v:IsA("Accessory")then local h=v:FindFirstChild("Handle")if h and h:IsA("BasePart")then if h.Size.Magnitude>20 then is=true rs="Huge Hat"break elseif h.Size.Magnitude>10 or(h.Transparency<0.1 and h.Material==Enum.Material.Neon)then ig=true rs="Glitch Acc"end end end end if not is and not ig then local h=p.Character:FindFirstChildOfClass("Humanoid")if h then local bw=h:FindFirstChild("BodyWidthScale")local bh=h:FindFirstChild("BodyHeightScale")if(bw and bw.Value>2)or(bh and bh.Value>2)then is=true rs="Glitch Av"end end end IEP(p)if ST.ESP.ch[p]then ST.ESP.ch[p].is=is ST.ESP.ch[p].ig=ig ST.ESP.ch[p].rs=rs end if mh then local hr=GCR(p.Character)local h=p.Character:FindFirstChildOfClass("Humanoid")if hr and h and h.Health>0 then local d=(hr.Position-mh.Position).Magnitude if d<=ST.ESP.md then table.insert(tmp,{p=p,hr=hr,d=d,c=p.Character})end end end end end table.sort(tmp,function(a,b)return a.d<b.d end)eL=tmp end task.wait(0.3)end end)
TC(RS.RenderStepped:Connect(function()if not ST.ESP.ac then return end local mh=GCR(LP.Character)if not mh then return end local vp=CA.ViewportSize local ct=Vector2.new(vp.X/2,vp.Y/2)for _,c in pairs(ST.ESP.ch)do pcall(function()if c.tx then c.tx.Visible=false end if c.tr then c.tr.Visible=false end for _,l in ipairs(c.bx)do if l then l.Visible=false end end if c.hl then c.hl.Enabled=false end end)end local hc=0 for _,d in ipairs(eL)do local p,c,hr,dist=d.p,d.c,d.hr,d.d local c2=ST.ESP.ch[p]if not c2 then continue end local pos,vis=CA:WorldToViewportPoint(hr.Position)if not vis then continue end local sus,glitch=c2.is,c2.ig local uhl=sus or glitch or ST.ESP.hl local txt=string.format("%s\n[%dm]",p.DisplayName,math.floor(dist))if sus or glitch then txt=txt.."\n⚠ "..c2.rs end local ccol=sus and ST.ESP.bS or(glitch and ST.ESP.bG or ST.ESP.nC)local tcol=sus and ST.ESP.tS or(glitch and ST.ESP.tG or ST.ESP.tN)local bcol=sus and ST.ESP.bS or(glitch and ST.ESP.bG or ST.ESP.bN)pcall(function()if c2.tx then c2.tx.Text=txt c2.tx.Color=ccol c2.tx.Position=Vector2.new(pos.X,pos.Y-45)c2.tx.Visible=true end if ST.ESP.tm~="OFF"and c2.tr then local org=Vector2.new(vp.X/2,vp.Y)if ST.ESP.tm=="Center"then org=ct elseif ST.ESP.tm=="Mouse"then local m=UI:GetMouseLocation()org=Vector2.new(m.X,m.Y)end c2.tr.From=org c2.tr.To=Vector2.new(pos.X,pos.Y)c2.tr.Color=tcol c2.tr.Visible=true end end)if uhl and hc<30 then hc=hc+1 pcall(function()local top,tv=CA:WorldToViewportPoint(hr.Position+Vector3.new(0,3,0))local bot,bv=CA:WorldToViewportPoint(hr.Position-Vector3.new(0,3.5,0))if tv and bv and #c2.bx==4 then local bh=math.abs(top.Y-bot.Y)local bw=bh*0.6 c2.bx[1].From=Vector2.new(pos.X-bw/2,top.Y)c2.bx[1].To=Vector2.new(pos.X+bw/2,top.Y)c2.bx[2].From=Vector2.new(pos.X+bw/2,top.Y)c2.bx[2].To=Vector2.new(pos.X+bw/2,bot.Y)c2.bx[3].From=Vector2.new(pos.X+bw/2,bot.Y)c2.bx[3].To=Vector2.new(pos.X-bw/2,bot.Y)c2.bx[4].From=Vector2.new(pos.X-bw/2,bot.Y)c2.bx[4].To=Vector2.new(pos.X-bw/2,top.Y)for i=1,4 do c2.bx[i].Color=bcol c2.bx[i].Visible=true end end end)pcall(function()if not c2.hl or c2.hl.Parent~=c then if c2.hl then c2.hl:Destroy()end c2.hl=Instance.new("Highlight",c)c2.hl.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop end if c2.hl then c2.hl.FillColor=bcol c2.hl.OutlineColor=Color3.new(1,1,1)c2.hl.Enabled=true end end)end end end end))
local function GLR()local r=RPS:FindFirstChild("Remotes")if not r then return nil,nil end return r:FindFirstChild("GetLikeDataRemote"),r:FindFirstChild("LikePlayerEvent")end
local function LRP()local _,lp=GLR()if not lp then return false,"Remote not found"end local mr=GR()local tg={}for _,p in pairs(PL:GetPlayers())do if p~=LP then if ST.AL.rd>0 and mr then local tr=p.Character and p.Character:FindFirstChild("HumanoidRootPart")if tr then local d=(tr.Position-mr.Position).Magnitude if d<=ST.AL.rd then table.insert(tg,p)end end else table.insert(tg,p)end end end if #tg==0 then return false,"No players"end local t if #tg==1 then t=tg[1]else repeat t=tg[math.random(1,#tg)]until t~=ST.AL.lt or #tg<=1 end ST.AL.lt=t local s=pcall(function()lp:FireServer(t)end)if s then ST.AL.ct=ST.AL.ct+1 return true,t.DisplayName end return false,"Failed"end
local function SAL()if ST.AL.ac then return end ST.AL.ac=true ST.AL.th=task.spawn(function()while ST.AL.ac and getgenv()._XKID_RUNNING do local o,r=LRP()if o then N("Auto Like",r.." | Total: "..ST.AL.ct,1.5,"heart")end local cd=math.random(ST.AL.mn*10,ST.AL.mx*10)/10 task.wait(cd)end ST.AL.th=nil end)N("Auto Like","ON",2,"heart")end
local function STAL()ST.AL.ac=false if ST.AL.th then task.cancel(ST.AL.th)ST.AL.th=nil end N("Auto Like","OFF",1.5,"heart")end
local Win=W:CreateWindow({Title="XKID HUB V2.1",Icon="bluetooth",Author="@WTF.XKID",Folder="XKIDHub",Size=UDim2.fromOffset(360,320),Transparent=true,Theme="Crimson",SideBarWidth=160,User={Enabled=true,Anonymous=false},Topbar={Height=40,ButtonsType="Default"}})
pcall(function()W:SetFont("rbxassetid://12187376357")W:SetNotificationLower(true)Win.User:SetDisplayName(LP.DisplayName)Win.User:SetUsername("@"..LP.Name)end)
Win:EditOpenButton({Title="XKID V2.1",Icon="github",CornerRadius=UDim.new(1,0),StrokeThickness=2,StrokeColor=Color3.fromRGB(255,70,120),Enabled=true,Draggable=true,Scale=0.72})
local fpsT=Win:Tag({Title="FPS: -- | Ping: --",Color=Color3.fromRGB(255,215,0),Icon="github"})
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(1)if fpsT and fpsT.SetTitle then fpsT:SetTitle("FPS: "..SFPS.." | Ping: "..SP.."ms")end end end)
local tInfo=Win:Tab({Title="Informasi",Icon="activity"})
local function GE()pcall(function()local e=identifyexecutor()if e and e~=""then return e end end)pcall(function()local e=getexecutorname()if e and e~=""then return e end end)return E.name end
local eN=GE()local aA=LP.AccountAge.." days"local aI="rbxthumb://type=AvatarHeadShot&id="..LP.UserId.."&w=420&h=420"
local aP=tInfo:Paragraph({Title="YooWssp!!, "..LP.DisplayName,Desc="Executor: "..eN.."\nAccount Age: "..aA.."\nUserID: "..LP.UserId.."\nStatus: "..(LP.MembershipType==Enum.MembershipType.Premium and"Premium"or"Normal").."\nAnti AFK: ON ✅",Image=aI,ImageSize=80})
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(1)pcall(function()aP:SetDesc("Executor: "..eN.."\nAccount Age: "..aA.."\nUserID: "..LP.UserId.."\nStatus: "..(LP.MembershipType==Enum.MembershipType.Premium and"Premium"or"Normal").."\nAnti AFK: "..(AFK.ac and"ON ✅"or"OFF ❌"))end)end end)
local iP=tInfo:Paragraph({Title="💀 "..LP.DisplayName.."\n⚡ "..MB(SFPS,120,10).." "..SFPS.." FPS\n📡 "..MB(math.max(1,200-SP),200,10).." "..SP.."ms\n🕐 "..MB(os.difftime(os.time(),START_TIME)%3600,3600,10).." "..FT(os.difftime(os.time(),START_TIME)),Desc="👤 "..LP.DisplayName.."\n📱 "..(MO and"Mobile"or"PC").." | 🚀 "..eN.."\n\n🎮 "..(CMN or"Loading...").."\n👥 "..MB(#PL:GetPlayers(),PL.MaxPlayers,10).." "..#PL:GetPlayers().."/"..PL.MaxPlayers.." Players\n\n🌐 discord.gg/bzumc2u96"})
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(1)pcall(function()iP:SetTitle("💀 "..LP.DisplayName.."\n⚡ "..MB(SFPS,120,10).." "..SFPS.." FPS\n📡 "..MB(math.max(1,200-SP),200,10).." "..SP.."ms\n🕐 "..MB(os.difftime(os.time(),START_TIME)%3600,3600,10).." "..FT(os.difftime(os.time(),START_TIME)))end)end end)
tInfo:Section({Title="🔗 Discord",Icon="message-circle",Box=true}):Button({Title="Copy Discord Link",Desc="discord.gg/bzumc2u96",Callback=function()pcall(function()setclipboard("https://discord.gg/bzumc2u96")end)N("System","Link copied",2,"copy")end})
local tChar=Win:Tab({Title="Character",Icon="fingerprint"})
tChar:Button({Title="Refresh Character 🔄",Desc="Reload character like /re",Callback=RC})
local sMov=tChar:Section({Title="Movement",Icon="activity",Box=true})
sMov:Slider({Title="Walk Speed",Step=1,Value={Min=16,Max=500,Default=16},Callback=function(v)ST.Move.ws=v if GH()then GH().WalkSpeed=v end end})
sMov:Slider({Title="Jump Power",Step=1,Value={Min=50,Max=500,Default=50},Callback=function(v)ST.Move.jp=v local h=GH()if h then h.UseJumpPower=true h.JumpPower=v end end})
sMov:Toggle({Title="Infinite Jump",Default=false,Callback=function(v)if v then ST.Move.infJ=TC(UI.JumpRequest:Connect(function()if GH()then GH():ChangeState(Enum.HumanoidStateType.Jumping)end end))else if ST.Move.infJ then ST.Move.infJ:Disconnect()ST.Move.infJ=nil end end N("Infinite Jump",v and"ON"or"OFF",1.5,"arrow-big-up")end})
local sAW=tChar:Section({Title="Auto Walk",Icon="play",Box=true})
sAW:Toggle({Title="Auto Walk",Default=false,Callback=function(v)if v then SAW()else STAW()end end})
sAW:Slider({Title="Walk Speed",Step=1,Value={Min=1,Max=100,Default=16},Callback=function(v)ST.Move.aws=v if ST.Move.aw then local h=GH()if h then h.WalkSpeed=v end end end})
sAW:Paragraph({Title="Info",Desc="Character walks forward automatically\nMove manually to override"})
local sAbi=tChar:Section({Title="Abilities",Icon="zap",Box=true})
sAbi:Toggle({Title="Fly",Default=false,Callback=function(v)TF(v)end})
sAbi:Slider({Title="Fly Speed",Step=1,Value={Min=10,Max=300,Default=60},Callback=function(v)ST.Move.flyS=v end})
local ncC=nil
sAbi:Toggle({Title="NoClip",Default=false,Callback=function(v)ST.Move.ncp=v if v then if not ncC then ncC=TC(RS.Heartbeat:Connect(function()if not ST.Move.ncp then return end if LP.Character then for _,p in pairs(LP.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=false end end end end))end else if ncC then ncC:Disconnect()ncC=nil end if LP.Character then for _,p in pairs(LP.Character:GetDescendants())do if p:IsA("BasePart")then p.CanCollide=true end end end end N("NoClip",v and"ON"or"OFF",1.5,"ghost")end})
local sFling=tChar:Section({Title="Hard Fling (Safe)",Icon="rotate-cw",Box=true})
sFling:Toggle({Title="Hard Fling",Default=false,Callback=function(v)if v then SHF()else STHF()end end})
sFling:Dropdown({Title="Fling Mode",Values={"Spin","Shake"},Default="Spin",Callback=function(v)ST.HF.md=v N("Fling Mode",v,1.5,"rotate-cw")end})
sFling:Slider({Title="Fling Power",Step=500,Value={Min=1000,Max=50000,Default=10000},Callback=function(v)ST.HF.pw=v end})
local tTP=Win:Tab({Title="Teleport",Icon="map-pin-x-inside"})
local sDTP=tTP:Section({Title="Direct Teleport",Icon="map-pin",Box=true})
sDTP:Toggle({Title="Smart TP",Desc="Equip tool → tap to toggle mode → tap to TP",Default=false,Callback=TSTP})
local sTTP=tTP:Section({Title="Target Teleport",Icon="crosshair",Box=true})
local tpT=""
sTTP:Input({Title="Search Player",Placeholder="Type name...",Callback=function(v)tpT=v end})
sTTP:Button({Title="Execute TP",Desc="Teleport to target",Callback=function()pcall(function()if tpT==""then N("Teleport","Input target!",2,"circle-alert")return end local t=nil for _,p in pairs(PL:GetPlayers())do if p~=LP and(string.find(string.lower(p.Name),string.lower(tpT))or string.find(string.lower(p.DisplayName),string.lower(tpT)))then t=p break end end if not t or not t.Parent or not t.Character then N("Teleport","Invalid Target",2,"circle-alert")return end local thr=GCR(t.Character)local mhr=GR()if not thr or not mhr then return end mhr.CFrame=thr.CFrame*CFrame.new(0,0,3)+Vector3.new(0,2,0)N("Teleport",t.DisplayName,2,"map-pin")end)end})
sTTP:Dropdown({Title="Player List",Values=GDN(),Callback=function(v)tpT=tostring(v)end})
sTTP:Button({Title="Refresh List",Callback=function()N("Teleport","List refreshed",1.5,"map-pin")end})
local sCache=tTP:Section({Title="Coordinates Cache",Icon="save",Box=true})
local SL={}
for i=1,3 do local ix=i local hc=sCache:HStack({Columns=2})hc:Button({Title="💾 Save "..ix,Callback=function()local r=GR()if not r then return end SL[ix]=r.CFrame N("Slot "..ix,"Saved",1.5,"save")end})hc:Button({Title="📍 Load "..ix,Callback=function()if not SL[ix]then N("Slot "..ix,"Empty",1.5,"save")return end local r=GR()if not r then return end r.CFrame=SL[ix]N("Slot "..ix,"Loaded",1.5,"map-pin")end})end
local tSpec=Win:Tab({Title="Spectator",Icon="cctv"})
local sZoom=tSpec:Section({Title="Zoom Override",Icon="zoom-in",Box=true})
sZoom:Toggle({Title="Max Zoom Out",Default=false,Callback=function(v)pcall(function()LP.CameraMaxZoomDistance=v and 100000 or 400 end)N("Zoom",v and"Max"or"Default",1.5,"zoom-in")end})
local sSP=tSpec:Section({Title="Spectator Mode",Icon="eye",Box=true})
sSP:Dropdown({Title="Select Target",Values=GDNS(),Callback=function(v)local s=tostring(v)if s=="[Self]"then Sp.tg=LP Sp.is=true Sp.oy=0 Sp.op=20 Sp.fy=0 N("Spectator","Self",1.5,"eye")else local p=FPD(s)if p then Sp.tg=p Sp.is=false if p.Character and p.Character:FindFirstChild("HumanoidRootPart")then local _,ry,_=p.Character.HumanoidRootPart.CFrame:ToEulerAnglesYXZ()Sp.oy=math.deg(ry)Sp.op=20 Sp.fy=math.deg(ry)end N("Spectator",p.DisplayName,1.5,"eye")end end end})
sSP:Button({Title="Refresh Target List",Callback=function()N("Spectator","List refreshed",1.5,"eye")end})
sSP:Toggle({Title="Enable Spectate",Default=false,Callback=function(v)if SSs.ac then TSS(false)end Sp.ac=v if v then if not Sp.tg or not Sp.tg.Character then if Sp.is and LP.Character then else Sp.ac=false N("Error","No target",2,"circle-alert")return end end Sp.of=CA.FieldOfView SSPC()SSPL()N("Spectator","ON",2,"eye")else STSPL()STSPC()CA.CameraType=Enum.CameraType.Custom CA.FieldOfView=Sp.of N("Spectator","OFF",1.5,"eye")end end})
sSP:Toggle({Title="First Person View",Default=false,Callback=function(v)Sp.md=v and"first"or"third"N("Spectator",v and"First Person"or"Third Person",1.5,"eye")end})
sSP:Slider({Title="Distance",Step=1,Value={Min=3,Max=30,Default=8},Callback=function(v)Sp.ds=v end})
local tCine=Win:Tab({Title="Cinematic",Icon="aperture"})
local sSS=tCine:Section({Title="🎥 Self-Spectate",Icon="camera",Box=true})
sSS:Toggle({Title="Enable Self-Spectate",Desc="1-finger orbit | 2-finger zoom | Mouse right-drag",Default=false,Callback=TSS})
sSS:Dropdown({Title="Preset Mode",Values={"Manual","Slow Orbit","Vertical Swing","Figure 8","Cinematic Drift","Top Down","First Person"},Default="Manual",Callback=function(v)SSs.md=v N("Self-Spec","Mode: "..v,1.5,"camera")end})
sSS:Slider({Title="Distance / Radius",Step=0.5,Value={Min=3,Max=30,Default=8},Callback=function(v)SSs.rd=v SSs.ds=v end})
sSS:Slider({Title="Height",Step=0.5,Value={Min=-10,Max=20,Default=3},Callback=function(v)SSs.he=v end})
sSS:Slider({Title="Speed",Step=0.1,Value={Min=0.1,Max=5,Default=1},Callback=function(v)SSs.sp=v end})
local sFC=tCine:Section({Title="Drone Engine + Hide UI",Icon="video",Box=true})
sFC:Toggle({Title="Enable Freecam",Default=false,Callback=function(v)if v and SSs.ac then TSS(false)end FC.ac=v if v then local cf=CA.CFrame FC.pos=cf.Position FC.pi=0 FC.ya=0 FC.ro=0 cV=Vector3.zero yV=0 pV=0 rV=0 hV=0 fmJ=Vector2.zero local h,r=GH(),GR()if h then FC.sWS=h.WalkSpeed FC.sJP=h.JumpPower h.WalkSpeed=0 h.JumpPower=0 end if r then r.Anchored=true FC.wa=true end FC.of=CA.FieldOfView SFCC()SFCL()if getgenv()._XKID_FCUI then getgenv()._XKID_FCUI.Enabled=true end FC_UH=false eBtn.Text="👁"for _,b in ipairs(fB)do b.Visible=true end N("Freecam","ON",2,"video")else FCFC()N("Freecam","OFF",1.5,"video")end end})
sFC:Slider({Title="Camera Speed",Step=0.5,Value={Min=1,Max=20,Default=3},Callback=function(v)FC.sp=v end})
sFC:Slider({Title="Sensitivity",Step=0.05,Value={Min=0.1,Max=1.0,Default=0.25},Callback=function(v)FC.se=v end})
sFC:Toggle({Title="Hide All UI (Cinematic)",Default=false,Callback=function(v)if getgenv()._XKID_UI_LOADING then return end if v then ST.Cin.hu=true ST.Cin.cg={}for _,g in pairs(LP.PlayerGui:GetChildren())do if g:IsA("ScreenGui")and g.Enabled then table.insert(ST.Cin.cg,g)g.Enabled=false end end pcall(function()SG:SetCoreGuiEnabled(Enum.CoreGuiType.All,false)end)else ST.Cin.hu=false for _,g in pairs(ST.Cin.cg)do if g and g.Parent then g.Enabled=true end end ST.Cin.cg={}pcall(function()SG:SetCoreGuiEnabled(Enum.CoreGuiType.All,true)end)end N("Cinematic",v and"UI Hidden"or"UI Shown",1.5,"film")end})
local tVis=Win:Tab({Title="Visuals",Icon="moon-star"})
local sPres=tVis:Section({Title="Presets",Icon="palette",Box=true})
sPres:Dropdown({Title="Select Filter",Values={"Default","Custom","Mendung","CoolBlue","SoftFade","FullBright","Night","Senja","Golden"},Default="Default",Callback=AF})
local sFX=tVis:Section({Title="Simple Custom FX",Icon="sliders",Box=true})
sFX:Slider({Title="Red",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v)ST.CF.r=v ACF()end})
sFX:Slider({Title="Green",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v)ST.CF.g=v ACF()end})
sFX:Slider({Title="Blue",Step=1,Value={Min=0,Max=255,Default=255},Callback=function(v)ST.CF.b=v ACF()end})
sFX:Slider({Title="Saturation",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v)ST.CF.st=v ACF()end})
sFX:Slider({Title="Contrast",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v)ST.CF.ct=v ACF()end})
sFX:Slider({Title="Brightness",Step=0.05,Value={Min=-1,Max=1,Default=0},Callback=function(v)ST.CF.br=v ACF()end})
sFX:Slider({Title="Exposure",Step=0.1,Value={Min=-5,Max=5,Default=0},Callback=function(v)ST.CF.ex=v ACF()end})
sFX:Slider({Title="Bloom",Step=0.1,Value={Min=0,Max=2,Default=0},Callback=function(v)ST.CF.bl=v ACF()end})
sFX:Slider({Title="Bloom Size",Step=1,Value={Min=0,Max=100,Default=24},Callback=function(v)ST.CF.bs=v ACF()end})
sFX:Slider({Title="Time",Step=0.5,Value={Min=0,Max=24,Default=14},Callback=function(v)ST.CF.ti=v ACF()end})
sFX:Button({Title="Reset FX",Callback=function()ST.CF={r=255,g=255,b=255,st=0,ct=0,br=0,ex=0,bl=0,bs=24,ti=14}ACF()N("Visuals","FX Reset",2,"rotate-ccw")end})
local tESP=Win:Tab({Title="ESP",Icon="scan-search"})
local sDet=tESP:Section({Title="Detection System",Icon="radar",Box=true})
sDet:Toggle({Title="Enable Radar",Default=false,Callback=function(v)ST.ESP.ac=v if not v and ST.ESP.ch then for _,c in pairs(ST.ESP.ch)do pcall(function()if c.tx then c.tx.Visible=false end if c.tr then c.tr.Visible=false end for _,l in ipairs(c.bx)do if l then l.Visible=false end end if c.hl then c.hl.Enabled=false end end)end end N("ESP",v and"ON"or"OFF",1.5,"radar")end})
sDet:Dropdown({Title="Tracer Origin",Values={"Bottom","Center","Mouse","OFF"},Default="Bottom",Callback=function(v)ST.ESP.tm=v N("ESP","Tracer: "..v,1.5,"radar")end})
sDet:Toggle({Title="Highlight Entity",Default=false,Callback=function(v)ST.ESP.hl=v N("ESP","Highlight "..(v and"ON"or"OFF"),1.5,"radar")end})
sDet:Slider({Title="Scan Distance",Step=10,Value={Min=50,Max=500,Default=300},Callback=function(v)ST.ESP.md=v end})
local sCol=tESP:Section({Title="Color Config",Icon="palette",Box=true})
sCol:Dropdown({Title="Normal",Values={"Hijau","Merah","Biru","Kuning","Ungu","Cyan","Orange","Pink","Putih","Hitam"},Default="Hijau",Callback=function(v)if CM[v]then ST.ESP.tN=CM[v]ST.ESP.bN=CM[v]end N("ESP","Normal: "..v,1.5,"palette")end})
sCol:Dropdown({Title="Suspect",Values={"Merah","Crimson","Hijau","Biru","Kuning","Ungu","Cyan","Orange","Pink","Putih","Hitam"},Default="Crimson",Callback=function(v)if CM[v]then ST.ESP.tS=CM[v]ST.ESP.bS=CM[v]end N("ESP","Suspect: "..v,1.5,"palette")end})
sCol:Dropdown({Title="Glitch",Values={"Orange","Merah","Hijau","Biru","Kuning","Ungu","Cyan","Pink","Putih","Hitam"},Default="Orange",Callback=function(v)if CM[v]then ST.ESP.tG=CM[v]ST.ESP.bG=CM[v]end N("ESP","Glitch: "..v,1.5,"palette")end})
local tLog=Win:Tab({Title="Logger",Icon="square-terminal"})
local sChat=tLog:Section({Title="Chat Logger",Icon="message-square",Box=true})
sChat:Toggle({Title="Enable Logger",Default=false,Callback=function(v)ST.UL.cl=v if not v then pcall(function()cLP:SetDesc("Logger disabled")end)end N("Logger",v and"ON"or"OFF",1.5,"terminal")end})
cTL=sChat:Paragraph({Title="Targets",Desc="None"})
cTD=sChat:Dropdown({Title="Select Targets",Multi=true,AllowNone=true,Values=GDN(),Callback=function(s)ST.UL.ctg={}if s and typeof(s)=="table"then for _,n in ipairs(s)do table.insert(ST.UL.ctg,tostring(n))end end if #ST.UL.ctg>0 then pcall(function()cTL:SetDesc("Tracking: "..table.concat(ST.UL.ctg,", "))end)else pcall(function()cTL:SetDesc("None")end)end end})
sChat:Button({Title="Clear Targets",Callback=function()ST.UL.ctg={}pcall(function()cTL:SetDesc("None")end)pcall(function()cTD:SetValues({});task.wait(0.05);cTD:SetValues(GDN())end)N("Logger","Targets cleared",1.5,"terminal")end})
sChat:Button({Title="Refresh List",Callback=function()pcall(function()cTD:Refresh(GDN(),true)end)N("Logger","List refreshed",1.5,"terminal")end})
cLP=sChat:Paragraph({Title="Console",Desc="Belum ada chat..."})
sChat:Button({Title="Clear Log",Callback=function()ST.UL.ch={}pcall(function()cLP:SetDesc("Belum ada chat...")end)N("Logger","Log cleared",1.5,"terminal")end})
task.spawn(function()local function OC(sn,msg)if not ST.UL.cl then return end if #ST.UL.ctg==0 then return end local cs=sn:lower():match("^%s*(.-)%s*$")for _,t in ipairs(ST.UL.ctg)do local ct=t:lower():match("^%s*(.-)%s*$")if cs==ct then local e=string.format("[%s] %s: %s",os.date("%H:%M:%S"),sn,msg)table.insert(ST.UL.ch,e)if #ST.UL.ch>50 then table.remove(ST.UL.ch,1)end N("Chat",sn..": "..msg,2,"message-circle")break end end end if TCS.ChatVersion==Enum.ChatVersion.TextChatService then pcall(function()TC(TCS.MessageReceived:Connect(function(m)if m.TextSource then OC(m.TextSource.Name,m.Text)end end))end)end local function CLC(p)pcall(function()TC(p.Chatted:Connect(function(m)OC(p.DisplayName,m)end))end)end for _,p in pairs(PL:GetPlayers())do if p~=LP then CLC(p)end end TC(PL.PlayerAdded:Connect(function(p)if p~=LP then CLC(p)end end))end)
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(0.5)if cLP and ST.UL.cl then pcall(function()local t=table.concat(ST.UL.ch,"\n")if #t>2000 then t=t:sub(-2000)end if #t==0 then t="Belum ada chat..."end cLP:SetDesc(t)end)end end end)
local tProt=Win:Tab({Title="Protection",Icon="shield-half"})
local sProt=tProt:Section({Title="Protection Protocols",Icon="shield-check",Box=true})
sProt:Toggle({Title="Anti AFK (Smart)",Default=false,Callback=function(v)if v then SAFK()else STAFK()end end})
sProt:Button({Title="Stuck Fix",Desc="Get unstuck from walls/ground",Callback=function()local r,h=GR(),GH()if r then r.Anchored=false r.CFrame=r.CFrame+Vector3.new(0,3,0)end if h then h.Sit=false h:ChangeState(Enum.HumanoidStateType.Jumping)end N("Protection","Stuck fix applied",2,"wrench")end})
local sSrv=tProt:Section({Title="Server Control",Icon="server",Box=true})
sSrv:Button({Title="Force Rejoin",Desc="Rejoin current server",Callback=function()pcall(function()TP:TeleportToPlaceInstance(game.PlaceId,game.JobId,LP)end)N("Server","Rejoining...",2,"log-in")end})
sSrv:Button({Title="Server Hop",Desc="Find a new server",Callback=function()pcall(function()local req=getgenv()._XKID_REQUEST or H if not req then N("Error","HTTP not supported",2,"circle-alert")return end local res=req({Url="https://games.roblox.com/v1/games/"..game.PlaceId.."/servers/Public?sortOrder=Desc&limit=100",Method="GET"})if res.StatusCode==200 then local b=HS:JSONDecode(res.Body)if b and b.data then for _,v in ipairs(b.data)do if v.playing>0 and v.playing<v.maxPlayers and v.id~=game.JobId then TP:TeleportToPlaceInstance(game.PlaceId,v.id,LP)N("Server","Hopping...",2,"shuffle")return end end end end end)end})
local sPerf=tProt:Section({Title="Performance",Icon="gauge",Box=true})
local gfxM={[1]="Level01",[2]="Level02",[3]="Level03",[4]="Level04",[5]="Level05",[6]="Level06",[7]="Level07",[8]="Level08",[9]="Level09",[10]="Level10"}
sPerf:Slider({Title="Quality Level",Step=1,Value={Min=1,Max=10,Default=2},Callback=function(v)if gfxM[v]then pcall(function()settings().Rendering.QualityLevel=Enum.QualityLevel[gfxM[v]]end)end N("Graphics",gfxM[v],1.5,"gauge")end})
sPerf:Dropdown({Title="FPS Cap",Values={"30","60","120","144","240","Unlimited"},Default="120",Callback=function(v)if v=="Unlimited"then F(9999)else F(tonumber(v))end N("Graphics",v.." FPS",1.5,"gauge")end})
local aCache={lvl=nil,sh=true,br=5,ct=14,fe=100000,mats={},txs={}}
sPerf:Toggle({Title="FPS Boost",Default=false,Callback=function(v)ST.Sec.al=v if v then pcall(function()aCache.lvl=settings().Rendering.QualityLevel end)aCache.sh=LT.GlobalShadows aCache.br=LT.Brightness aCache.ct=LT.ClockTime aCache.fe=LT.FogEnd pcall(function()settings().Rendering.QualityLevel=1 end)LT.GlobalShadows=false LT.Brightness=1 LT.FogEnd=100000 for _,o in pairs(workspace:GetDescendants())do if o:IsA("BasePart")then aCache.mats[o]=o.Material o.Material=Enum.Material.SmoothPlastic elseif o:IsA("Decal")or o:IsA("Texture")or o:IsA("ParticleEmitter")or o:IsA("Trail")then aCache.txs[o]=o.Enabled o.Enabled=false end end N("Performance","FPS Boost ON",2,"zap")else pcall(function()if aCache.lvl then settings().Rendering.QualityLevel=aCache.lvl end end)LT.GlobalShadows=aCache.sh LT.Brightness=aCache.br LT.ClockTime=aCache.ct LT.FogEnd=aCache.fe for o,mat in pairs(aCache.mats)do if o and o.Parent then o.Material=mat end end for o,en in pairs(aCache.txs)do if o and o.Parent then o.Enabled=en end end aCache.mats={}aCache.txs={}N("Performance","Graphics restored",2,"zap")end end})
local sCam=tProt:Section({Title="Camera Lock",Icon="lock",Box=true})
sCam:Toggle({Title="Force Shift Lock",Default=false,Callback=function(v)TSL(v)end})
local tSet=Win:Tab({Title="Settings",Icon="panels-top-left"})
local sTheme=tSet:Section({Title="🎨 Theme",Icon="palette",Box=true})
sTheme:Dropdown({Title="UI Theme",Values={"Dark","Light","Rose","Sky","Emerald","Violet","Red","Amber","Indigo","Midnight","Crimson"},Default="Crimson",Callback=function(v)W:SetTheme(v)end})
local sFile=tSet:Section({Title="File Management",Icon="folder",Box=true})
local cfgN="XKID_Config_V2"local curCfg="No config"
sFile:Input({Title="Config Name",Value="XKID_Config_V2",Callback=function(v)cfgN=v end})
local function SCF()if E.wf then pcall(function()if not isfolder("XKID_HUB")then makefolder("XKID_HUB")end local d={Move={ws=ST.Move.ws,jp=ST.Move.jp,flyS=ST.Move.flyS,aws=ST.Move.aws},ESP={tm=ST.ESP.tm,md=ST.ESP.md,hl=ST.ESP.hl},Sec={sl=ST.Sec.sl,al=ST.Sec.al},HF={pw=ST.HF.pw,md=ST.HF.md},SS={md=SSs.md,rd=SSs.rd,he=SSs.he,sp=SSs.sp},CF={r=ST.CF.r,g=ST.CF.g,b=ST.CF.b,st=ST.CF.st,ct=ST.CF.ct,br=ST.CF.br,ex=ST.CF.ex,bl=ST.CF.bl,bs=ST.CF.bs,ti=ST.CF.ti}}writefile("XKID_HUB/"..cfgN..".json",HS:JSONEncode(d))N("Config","Saved: "..cfgN,2,"save")end)else N("Config","Executor tidak support save",2,"circle-alert")end end
local function LCF(s)if s=="No config"then return end pcall(function()if E.rf and isfile and isfile("XKID_HUB/"..s..".json")then local d=HS:JSONDecode(readfile("XKID_HUB/"..s..".json"))if d then if d.Move then ST.Move.ws=d.Move.ws or 16 ST.Move.jp=d.Move.jp or 50 ST.Move.flyS=d.Move.flyS or 60 ST.Move.aws=d.Move.aws or 16 local h=GH()if h then h.WalkSpeed=ST.Move.ws h.UseJumpPower=true h.JumpPower=ST.Move.jp end end if d.ESP then ST.ESP.tm=d.ESP.tm or"Bottom"ST.ESP.md=d.ESP.md or 300 ST.ESP.hl=d.ESP.hl or false end if d.Sec and d.Sec.sl~=ST.Sec.sl then TSL(d.Sec.sl)end if d.HF then ST.HF.pw=d.HF.pw or 10000 ST.HF.md=d.HF.md or"Spin"end if d.SS then SSs.md=d.SS.md or"Manual"SSs.rd=d.SS.rd or 8 SSs.he=d.SS.he or 3 SSs.sp=d.SS.sp or 1 end if d.CF then for k,v in pairs(d.CF)do ST.CF[k]=v end ACF()end N("Config","Loaded: "..s,2,"folder-open")end end end)end
sFile:Button({Title="Save Config",Callback=SCF})
local cfgD=sFile:Dropdown({Title="Load Config",Values=GCL(),Callback=function(s)curCfg=s LCF(s)end})
sFile:Button({Title="Delete Config",Callback=function()if curCfg~="No config"and curCfg~=""and E.lf then pcall(function()if isfile and delfile and isfile("XKID_HUB/"..curCfg..".json")then delfile("XKID_HUB/"..curCfg..".json")pcall(function()cfgD:Refresh(GCL(),true)end)curCfg="No config"N("Config","Deleted",2,"trash-2")end end)end end})
sFile:Button({Title="Refresh Files",Callback=function()pcall(function()cfgD:Refresh(GCL(),true)end)N("Config","Files refreshed",1.5,"folder")end})
local sLike=tSet:Section({Title="Auto Like (Smart)",Icon="heart",Box=true})
sLike:Toggle({Title="Auto Like",Default=false,Callback=function(v)if v then SAL()else STAL()end end})
sLike:Slider({Title="Like Radius",Desc="0 = all",Step=10,Value={Min=0,Max=500,Default=100},Callback=function(v)ST.AL.rd=v end})
sLike:Slider({Title="Min Cooldown",Step=0.5,Value={Min=0.5,Max=10,Default=2},Callback=function(v)ST.AL.mn=v end})
sLike:Slider({Title="Max Cooldown",Step=0.5,Value={Min=1,Max=15,Default=6},Callback=function(v)ST.AL.mx=v end})
local ali=sLike:Paragraph({Title="Info",Desc="Total likes sent: 0"})
task.spawn(function()while getgenv()._XKID_RUNNING do task.wait(2)pcall(function()ali:SetDesc("Total likes sent: "..ST.AL.ct)end)end end)
task.delay(0.8,function()pcall(function()for _,t in pairs(Win.Tabs)do if t.Sections then for _,s in ipairs(t.Sections)do if s.Expand and type(s.Expand)=="function"then pcall(function()s:Expand()end)end end end end end)end)
pcall(function()settings().Rendering.QualityLevel=Enum.QualityLevel.Level02 end)
F(120)
task.spawn(function()task.wait(0.5)SAFK()task.wait(2)getgenv()._XKID_UI_LOADING=false N("System","XKID V2.1 AKTIF — Ready",3,"rocket")N("Anti AFK","AUTO ACTIVATED (7min Jump)",2,"shield-check")end)